// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: game.proto

package msg

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type RoomInfo struct {
	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name" bson:"name" msg:"name"`
	Id      int32  `protobuf:"varint,2,opt,name=id,proto3" json:"id" bson:"id" msg:"id"`
	Kind    int32  `protobuf:"varint,3,opt,name=kind,proto3" json:"kind" bson:"kind" msg:"kind"`
	Level   int32  `protobuf:"varint,4,opt,name=level,proto3" json:"level" bson:"level" msg:"level"`
	Cap     int32  `protobuf:"varint,5,opt,name=cap,proto3" json:"cap" bson:"cap" msg:"cap"`
	Ante    int64  `protobuf:"varint,6,opt,name=ante,proto3" json:"ante" bson:"ante" msg:"ante"`
	DoorMin int64  `protobuf:"varint,7,opt,name=doorMin,proto3" json:"doorMin" bson:"doorMin" msg:"doorMin"`
	DoorMax int64  `protobuf:"varint,8,opt,name=doorMax,proto3" json:"doorMax" bson:"doorMax" msg:"doorMax"`
	StayMin int64  `protobuf:"varint,9,opt,name=stayMin,proto3" json:"stayMin" bson:"stayMin" msg:"stayMin"`
	StayMax int64  `protobuf:"varint,10,opt,name=stayMax,proto3" json:"stayMax" bson:"stayMax" msg:"stayMax"`
	PlayMin int64  `protobuf:"varint,11,opt,name=playMin,proto3" json:"playMin" bson:"playMin" msg:"playMin"`
	PlayMax int64  `protobuf:"varint,12,opt,name=playMax,proto3" json:"playMax" bson:"playMax" msg:"playMax"`
	CoinKey string `protobuf:"bytes,13,opt,name=coinKey,proto3" json:"coinKey" bson:"coinKey" msg:"coinKey"`
	Icon    int32  `protobuf:"varint,14,opt,name=icon,proto3" json:"icon" bson:"icon" msg:"icon"`
	Online  int32  `protobuf:"varint,15,opt,name=online,proto3" json:"online" bson:"online" msg:"online"`
}

func (m *RoomInfo) Reset()         { *m = RoomInfo{} }
func (m *RoomInfo) String() string { return proto.CompactTextString(m) }
func (*RoomInfo) ProtoMessage()    {}
func (*RoomInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{0}
}
func (m *RoomInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RoomInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RoomInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RoomInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomInfo.Merge(m, src)
}
func (m *RoomInfo) XXX_Size() int {
	return m.Size()
}
func (m *RoomInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RoomInfo proto.InternalMessageInfo

func (m *RoomInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RoomInfo) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RoomInfo) GetKind() int32 {
	if m != nil {
		return m.Kind
	}
	return 0
}

func (m *RoomInfo) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *RoomInfo) GetCap() int32 {
	if m != nil {
		return m.Cap
	}
	return 0
}

func (m *RoomInfo) GetAnte() int64 {
	if m != nil {
		return m.Ante
	}
	return 0
}

func (m *RoomInfo) GetDoorMin() int64 {
	if m != nil {
		return m.DoorMin
	}
	return 0
}

func (m *RoomInfo) GetDoorMax() int64 {
	if m != nil {
		return m.DoorMax
	}
	return 0
}

func (m *RoomInfo) GetStayMin() int64 {
	if m != nil {
		return m.StayMin
	}
	return 0
}

func (m *RoomInfo) GetStayMax() int64 {
	if m != nil {
		return m.StayMax
	}
	return 0
}

func (m *RoomInfo) GetPlayMin() int64 {
	if m != nil {
		return m.PlayMin
	}
	return 0
}

func (m *RoomInfo) GetPlayMax() int64 {
	if m != nil {
		return m.PlayMax
	}
	return 0
}

func (m *RoomInfo) GetCoinKey() string {
	if m != nil {
		return m.CoinKey
	}
	return ""
}

func (m *RoomInfo) GetIcon() int32 {
	if m != nil {
		return m.Icon
	}
	return 0
}

func (m *RoomInfo) GetOnline() int32 {
	if m != nil {
		return m.Online
	}
	return 0
}

// 获取房间列表
type RoomListReq struct {
	Kind int32 `protobuf:"varint,1,opt,name=kind,proto3" json:"kind" bson:"kind" msg:"kind"`
}

func (m *RoomListReq) Reset()         { *m = RoomListReq{} }
func (m *RoomListReq) String() string { return proto.CompactTextString(m) }
func (*RoomListReq) ProtoMessage()    {}
func (*RoomListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{1}
}
func (m *RoomListReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RoomListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RoomListReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RoomListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomListReq.Merge(m, src)
}
func (m *RoomListReq) XXX_Size() int {
	return m.Size()
}
func (m *RoomListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomListReq.DiscardUnknown(m)
}

var xxx_messageInfo_RoomListReq proto.InternalMessageInfo

func (m *RoomListReq) GetKind() int32 {
	if m != nil {
		return m.Kind
	}
	return 0
}

type RoomListAck struct {
	Rooms []*RoomInfo `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms" bson:"rooms" msg:"rooms"`
}

func (m *RoomListAck) Reset()         { *m = RoomListAck{} }
func (m *RoomListAck) String() string { return proto.CompactTextString(m) }
func (*RoomListAck) ProtoMessage()    {}
func (*RoomListAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{2}
}
func (m *RoomListAck) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RoomListAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RoomListAck.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RoomListAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomListAck.Merge(m, src)
}
func (m *RoomListAck) XXX_Size() int {
	return m.Size()
}
func (m *RoomListAck) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomListAck.DiscardUnknown(m)
}

var xxx_messageInfo_RoomListAck proto.InternalMessageInfo

func (m *RoomListAck) GetRooms() []*RoomInfo {
	if m != nil {
		return m.Rooms
	}
	return nil
}

// 用户连接房间
type LoginRoomReq struct {
	Id   int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id" bson:"id" msg:"id"`
	Args string `protobuf:"bytes,2,opt,name=args,proto3" json:"args" bson:"args" msg:"args"`
}

func (m *LoginRoomReq) Reset()         { *m = LoginRoomReq{} }
func (m *LoginRoomReq) String() string { return proto.CompactTextString(m) }
func (*LoginRoomReq) ProtoMessage()    {}
func (*LoginRoomReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{3}
}
func (m *LoginRoomReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LoginRoomReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LoginRoomReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LoginRoomReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRoomReq.Merge(m, src)
}
func (m *LoginRoomReq) XXX_Size() int {
	return m.Size()
}
func (m *LoginRoomReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRoomReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRoomReq proto.InternalMessageInfo

func (m *LoginRoomReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *LoginRoomReq) GetArgs() string {
	if m != nil {
		return m.Args
	}
	return ""
}

// 用户连接房间
type LoginRoomAck struct {
	Kind int32  `protobuf:"varint,1,opt,name=kind,proto3" json:"kind" bson:"kind" msg:"kind"`
	Room int32  `protobuf:"varint,2,opt,name=room,proto3" json:"room" bson:"room" msg:"room"`
	Tab  int32  `protobuf:"varint,3,opt,name=tab,proto3" json:"tab" bson:"tab" msg:"tab"`
	Seat int32  `protobuf:"varint,4,opt,name=seat,proto3" json:"seat" bson:"seat" msg:"seat"`
	Code int32  `protobuf:"varint,5,opt,name=code,proto3" json:"code" bson:"code" msg:"code"`
	Msg  string `protobuf:"bytes,6,opt,name=msg,proto3" json:"msg" bson:"msg" msg:"msg"`
}

func (m *LoginRoomAck) Reset()         { *m = LoginRoomAck{} }
func (m *LoginRoomAck) String() string { return proto.CompactTextString(m) }
func (*LoginRoomAck) ProtoMessage()    {}
func (*LoginRoomAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{4}
}
func (m *LoginRoomAck) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LoginRoomAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LoginRoomAck.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LoginRoomAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRoomAck.Merge(m, src)
}
func (m *LoginRoomAck) XXX_Size() int {
	return m.Size()
}
func (m *LoginRoomAck) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRoomAck.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRoomAck proto.InternalMessageInfo

func (m *LoginRoomAck) GetKind() int32 {
	if m != nil {
		return m.Kind
	}
	return 0
}

func (m *LoginRoomAck) GetRoom() int32 {
	if m != nil {
		return m.Room
	}
	return 0
}

func (m *LoginRoomAck) GetTab() int32 {
	if m != nil {
		return m.Tab
	}
	return 0
}

func (m *LoginRoomAck) GetSeat() int32 {
	if m != nil {
		return m.Seat
	}
	return 0
}

func (m *LoginRoomAck) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *LoginRoomAck) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

// 消息转发到房间失败，需要重新连接房间
type SendRoomFail struct {
	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code" bson:"code" msg:"code"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg" bson:"msg" msg:"msg"`
	Kind int32  `protobuf:"varint,3,opt,name=kind,proto3" json:"kind" bson:"kind" msg:"kind"`
	Room int32  `protobuf:"varint,4,opt,name=room,proto3" json:"room" bson:"room" msg:"room"`
}

func (m *SendRoomFail) Reset()         { *m = SendRoomFail{} }
func (m *SendRoomFail) String() string { return proto.CompactTextString(m) }
func (*SendRoomFail) ProtoMessage()    {}
func (*SendRoomFail) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{5}
}
func (m *SendRoomFail) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SendRoomFail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SendRoomFail.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SendRoomFail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendRoomFail.Merge(m, src)
}
func (m *SendRoomFail) XXX_Size() int {
	return m.Size()
}
func (m *SendRoomFail) XXX_DiscardUnknown() {
	xxx_messageInfo_SendRoomFail.DiscardUnknown(m)
}

var xxx_messageInfo_SendRoomFail proto.InternalMessageInfo

func (m *SendRoomFail) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *SendRoomFail) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *SendRoomFail) GetKind() int32 {
	if m != nil {
		return m.Kind
	}
	return 0
}

func (m *SendRoomFail) GetRoom() int32 {
	if m != nil {
		return m.Room
	}
	return 0
}

// 别的玩家信息
type User struct {
	Id   int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id" bson:"_id" msg:"id"`
	Icon int32  `protobuf:"varint,2,opt,name=icon,proto3" json:"icon" bson:"icon" msg:"icon"`
	Vip  int32  `protobuf:"varint,3,opt,name=vip,proto3" json:"vip" bson:"vip" msg:"vip"`
	Coin int64  `protobuf:"varint,4,opt,name=coin,proto3" json:"coin" bson:"coin" msg:"coin"`
	Name string `protobuf:"bytes,5,opt,name=name,proto3" json:"name" bson:"name" msg:"name"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{6}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_User.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return m.Size()
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetIcon() int32 {
	if m != nil {
		return m.Icon
	}
	return 0
}

func (m *User) GetVip() int32 {
	if m != nil {
		return m.Vip
	}
	return 0
}

func (m *User) GetCoin() int64 {
	if m != nil {
		return m.Coin
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*RoomInfo)(nil), "msg.RoomInfo")
	proto.RegisterType((*RoomListReq)(nil), "msg.RoomListReq")
	proto.RegisterType((*RoomListAck)(nil), "msg.RoomListAck")
	proto.RegisterType((*LoginRoomReq)(nil), "msg.LoginRoomReq")
	proto.RegisterType((*LoginRoomAck)(nil), "msg.LoginRoomAck")
	proto.RegisterType((*SendRoomFail)(nil), "msg.SendRoomFail")
	proto.RegisterType((*User)(nil), "msg.User")
}

func init() { proto.RegisterFile("game.proto", fileDescriptor_38fc58335341d769) }

var fileDescriptor_38fc58335341d769 = []byte{
	// 719 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x95, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0xeb, 0x38, 0x49, 0xdb, 0x6d, 0x0b, 0x92, 0x41, 0x65, 0x55, 0x55, 0x76, 0xe4, 0x03,
	0x44, 0x95, 0x48, 0xa5, 0x22, 0x71, 0xa8, 0xc4, 0xa1, 0x3d, 0x20, 0x21, 0x8a, 0x84, 0x16, 0x71,
	0x46, 0x1b, 0xdb, 0x35, 0xab, 0xc6, 0xbb, 0x21, 0x76, 0xab, 0xf4, 0x2d, 0x78, 0x0a, 0x8e, 0x3c,
	0x07, 0xe2, 0xd4, 0x23, 0x27, 0x0b, 0xb5, 0x47, 0x6e, 0x7e, 0x02, 0x34, 0xb3, 0xbb, 0x66, 0x5b,
	0x72, 0x48, 0x4f, 0x99, 0x19, 0xff, 0xdf, 0xce, 0xc4, 0x3b, 0x33, 0x26, 0x24, 0xe7, 0x45, 0x36,
	0x9a, 0xce, 0x54, 0xa5, 0x02, 0xbf, 0x28, 0xf3, 0x9d, 0xe7, 0xb9, 0xa8, 0x3e, 0x9f, 0x8f, 0x47,
	0x89, 0x2a, 0xf6, 0x73, 0x95, 0xab, 0x7d, 0x7c, 0x36, 0x3e, 0x3f, 0x45, 0x0f, 0x1d, 0xb4, 0x34,
	0x13, 0x7f, 0xef, 0x93, 0x35, 0xa6, 0x54, 0xf1, 0x46, 0x9e, 0xaa, 0x60, 0x44, 0xba, 0x92, 0x17,
	0x19, 0xf5, 0x06, 0xde, 0x70, 0xfd, 0x78, 0xa7, 0xa9, 0xa3, 0xed, 0x71, 0xa9, 0xe4, 0x61, 0x0c,
	0xd1, 0x78, 0x50, 0x94, 0xb9, 0x31, 0x19, 0xea, 0x82, 0xa7, 0xa4, 0x23, 0x52, 0xda, 0x19, 0x78,
	0xc3, 0xde, 0xf1, 0x76, 0x53, 0x47, 0x81, 0x56, 0x8b, 0xd4, 0x68, 0x45, 0x1a, 0xb3, 0x8e, 0x48,
	0xe1, 0xdc, 0x33, 0x21, 0x53, 0xea, 0xa3, 0xd2, 0x39, 0x17, 0xa2, 0x46, 0x8b, 0x26, 0x43, 0x5d,
	0x70, 0x40, 0x7a, 0x93, 0xec, 0x22, 0x9b, 0xd0, 0x2e, 0x02, 0xbb, 0x4d, 0x1d, 0x51, 0x0d, 0x60,
	0xd8, 0x10, 0xda, 0x66, 0x5a, 0x1a, 0xec, 0x11, 0x3f, 0xe1, 0x53, 0xda, 0x43, 0x82, 0x36, 0x75,
	0xf4, 0x58, 0x13, 0x09, 0x9f, 0x1a, 0x3d, 0x58, 0x0c, 0x44, 0x50, 0x0f, 0x97, 0x55, 0x46, 0xfb,
	0x03, 0x6f, 0xe8, 0xbb, 0xf5, 0x40, 0xd4, 0xa8, 0xd1, 0x64, 0xa8, 0x0b, 0x0e, 0xc9, 0x6a, 0xaa,
	0xd4, 0xec, 0x9d, 0x90, 0x74, 0x15, 0x91, 0x41, 0x53, 0x47, 0xbb, 0x1a, 0x31, 0x0f, 0x0c, 0x65,
	0x3d, 0x66, 0x81, 0x96, 0xe5, 0x73, 0xba, 0xb6, 0x90, 0xe5, 0x73, 0x97, 0xe5, 0x73, 0xcb, 0xf2,
	0x39, 0xb0, 0x65, 0xc5, 0x2f, 0x21, 0xef, 0xfa, 0x5d, 0xd6, 0x3c, 0x30, 0xac, 0xf5, 0x98, 0x05,
	0x5a, 0x96, 0xcf, 0x29, 0x59, 0xc8, 0xb6, 0x79, 0xad, 0xc7, 0x2c, 0x00, 0xec, 0x74, 0xa2, 0xf3,
	0x6e, 0xdc, 0x65, 0xcd, 0x03, 0xc3, 0x5a, 0x8f, 0x59, 0xa0, 0x65, 0xf9, 0x9c, 0x6e, 0x2e, 0x64,
	0xdb, 0xbc, 0xd6, 0x63, 0x16, 0x00, 0x36, 0x51, 0x42, 0xbe, 0xcd, 0x2e, 0xe9, 0x16, 0xb6, 0xa0,
	0xc3, 0x9a, 0x07, 0xf6, 0x2e, 0x8d, 0xc7, 0x2c, 0x00, 0x77, 0x2a, 0x12, 0x25, 0xe9, 0x83, 0xbb,
	0x3d, 0x06, 0x51, 0xdb, 0x8f, 0x60, 0x32, 0xd4, 0x05, 0x2f, 0x49, 0x5f, 0xc9, 0x89, 0x90, 0x19,
	0x7d, 0x88, 0x44, 0xd8, 0xd4, 0xd1, 0x8e, 0x26, 0x74, 0xdc, 0x30, 0xc6, 0x61, 0x46, 0x1d, 0xbf,
	0x22, 0x1b, 0x30, 0x2f, 0x27, 0xa2, 0xac, 0x58, 0xf6, 0xa5, 0x6d, 0x6d, 0x6f, 0xb9, 0xd6, 0x8e,
	0xdf, 0xff, 0xc3, 0x8f, 0x92, 0xb3, 0xe0, 0x88, 0xf4, 0x66, 0x4a, 0x15, 0x25, 0xf5, 0x06, 0xfe,
	0x70, 0xe3, 0x60, 0x6b, 0x54, 0x94, 0xf9, 0xc8, 0xce, 0xa3, 0xdb, 0xf8, 0xa8, 0x32, 0xe7, 0x69,
	0x9b, 0x69, 0x32, 0x3e, 0x25, 0x9b, 0x27, 0x2a, 0x17, 0x12, 0x28, 0xa8, 0x48, 0x0f, 0xa5, 0xb7,
	0xcc, 0x50, 0xf2, 0x59, 0x5e, 0xe2, 0xf8, 0xde, 0x1a, 0x76, 0x88, 0xda, 0x21, 0x00, 0x93, 0xa1,
	0x2e, 0xfe, 0xd6, 0x71, 0x12, 0x41, 0xed, 0xf7, 0xfc, 0xeb, 0xa0, 0x87, 0x8a, 0xcd, 0xbe, 0x70,
	0xf4, 0x10, 0x75, 0xfe, 0x5a, 0xcc, 0x50, 0x07, 0x13, 0x5d, 0xf1, 0xb1, 0x59, 0x1a, 0xce, 0x44,
	0x57, 0x7c, 0x6c, 0xd4, 0x60, 0x31, 0x10, 0xc1, 0xd9, 0x65, 0xc6, 0x2b, 0xb3, 0x30, 0x9c, 0xb3,
	0x21, 0x6a, 0xfb, 0x1c, 0x4c, 0x86, 0x3a, 0xd0, 0x27, 0x2a, 0xcd, 0xcc, 0xba, 0x70, 0xf4, 0x10,
	0x6d, 0x7b, 0x2c, 0x85, 0x0d, 0x00, 0x3f, 0x50, 0x4b, 0x51, 0xe6, 0xb8, 0x30, 0xd6, 0xdd, 0x5a,
	0x8a, 0x32, 0x37, 0x6a, 0xb0, 0x18, 0x88, 0xe2, 0x9f, 0x1e, 0xd9, 0xfc, 0x90, 0xc9, 0x14, 0xde,
	0xd3, 0x6b, 0x2e, 0x26, 0x6d, 0x32, 0xef, 0x7e, 0xc9, 0x3a, 0x4b, 0x24, 0xbb, 0xf7, 0x6a, 0xb5,
	0x97, 0xd0, 0x5d, 0xee, 0x12, 0xe2, 0x3f, 0x1e, 0xe9, 0x7e, 0x2c, 0xb3, 0x59, 0xf0, 0xcc, 0x69,
	0xab, 0x27, 0x4d, 0x1d, 0x3d, 0xd2, 0xd8, 0xa7, 0x45, 0x7d, 0x85, 0x83, 0xd8, 0x59, 0x72, 0x10,
	0xf7, 0x88, 0x7f, 0x21, 0xa6, 0xff, 0x5f, 0xf3, 0x85, 0xb0, 0x8b, 0x1b, 0x2c, 0x06, 0x22, 0xfd,
	0x26, 0x85, 0xc4, 0xea, 0xfd, 0xdb, 0x6f, 0xb2, 0x5d, 0x49, 0x68, 0x32, 0xd4, 0xb5, 0x1f, 0xb4,
	0xde, 0x72, 0x1f, 0xb4, 0x63, 0xfa, 0xe3, 0x3a, 0xf4, 0xae, 0xae, 0x43, 0xef, 0xf7, 0x75, 0xe8,
	0x7d, 0xbd, 0x09, 0x57, 0xae, 0x6e, 0xc2, 0x95, 0x5f, 0x37, 0xe1, 0xca, 0xb8, 0x8f, 0x9f, 0xcb,
	0x17, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x23, 0x71, 0x40, 0xc4, 0x70, 0x07, 0x00, 0x00,
}

func (m *RoomInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RoomInfo) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintGame(dAtA, i, uint64(len(m.Name)))
		i += copy(dAtA[i:], m.Name)
	}
	if m.Id != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintGame(dAtA, i, uint64(m.Id))
	}
	if m.Kind != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintGame(dAtA, i, uint64(m.Kind))
	}
	if m.Level != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintGame(dAtA, i, uint64(m.Level))
	}
	if m.Cap != 0 {
		dAtA[i] = 0x28
		i++
		i = encodeVarintGame(dAtA, i, uint64(m.Cap))
	}
	if m.Ante != 0 {
		dAtA[i] = 0x30
		i++
		i = encodeVarintGame(dAtA, i, uint64(m.Ante))
	}
	if m.DoorMin != 0 {
		dAtA[i] = 0x38
		i++
		i = encodeVarintGame(dAtA, i, uint64(m.DoorMin))
	}
	if m.DoorMax != 0 {
		dAtA[i] = 0x40
		i++
		i = encodeVarintGame(dAtA, i, uint64(m.DoorMax))
	}
	if m.StayMin != 0 {
		dAtA[i] = 0x48
		i++
		i = encodeVarintGame(dAtA, i, uint64(m.StayMin))
	}
	if m.StayMax != 0 {
		dAtA[i] = 0x50
		i++
		i = encodeVarintGame(dAtA, i, uint64(m.StayMax))
	}
	if m.PlayMin != 0 {
		dAtA[i] = 0x58
		i++
		i = encodeVarintGame(dAtA, i, uint64(m.PlayMin))
	}
	if m.PlayMax != 0 {
		dAtA[i] = 0x60
		i++
		i = encodeVarintGame(dAtA, i, uint64(m.PlayMax))
	}
	if len(m.CoinKey) > 0 {
		dAtA[i] = 0x6a
		i++
		i = encodeVarintGame(dAtA, i, uint64(len(m.CoinKey)))
		i += copy(dAtA[i:], m.CoinKey)
	}
	if m.Icon != 0 {
		dAtA[i] = 0x70
		i++
		i = encodeVarintGame(dAtA, i, uint64(m.Icon))
	}
	if m.Online != 0 {
		dAtA[i] = 0x78
		i++
		i = encodeVarintGame(dAtA, i, uint64(m.Online))
	}
	return i, nil
}

func (m *RoomListReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RoomListReq) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Kind != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintGame(dAtA, i, uint64(m.Kind))
	}
	return i, nil
}

func (m *RoomListAck) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RoomListAck) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Rooms) > 0 {
		for _, msg := range m.Rooms {
			dAtA[i] = 0xa
			i++
			i = encodeVarintGame(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *LoginRoomReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LoginRoomReq) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintGame(dAtA, i, uint64(m.Id))
	}
	if len(m.Args) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintGame(dAtA, i, uint64(len(m.Args)))
		i += copy(dAtA[i:], m.Args)
	}
	return i, nil
}

func (m *LoginRoomAck) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LoginRoomAck) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Kind != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintGame(dAtA, i, uint64(m.Kind))
	}
	if m.Room != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintGame(dAtA, i, uint64(m.Room))
	}
	if m.Tab != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintGame(dAtA, i, uint64(m.Tab))
	}
	if m.Seat != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintGame(dAtA, i, uint64(m.Seat))
	}
	if m.Code != 0 {
		dAtA[i] = 0x28
		i++
		i = encodeVarintGame(dAtA, i, uint64(m.Code))
	}
	if len(m.Msg) > 0 {
		dAtA[i] = 0x32
		i++
		i = encodeVarintGame(dAtA, i, uint64(len(m.Msg)))
		i += copy(dAtA[i:], m.Msg)
	}
	return i, nil
}

func (m *SendRoomFail) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SendRoomFail) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Code != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintGame(dAtA, i, uint64(m.Code))
	}
	if len(m.Msg) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintGame(dAtA, i, uint64(len(m.Msg)))
		i += copy(dAtA[i:], m.Msg)
	}
	if m.Kind != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintGame(dAtA, i, uint64(m.Kind))
	}
	if m.Room != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintGame(dAtA, i, uint64(m.Room))
	}
	return i, nil
}

func (m *User) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *User) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintGame(dAtA, i, uint64(m.Id))
	}
	if m.Icon != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintGame(dAtA, i, uint64(m.Icon))
	}
	if m.Vip != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintGame(dAtA, i, uint64(m.Vip))
	}
	if m.Coin != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintGame(dAtA, i, uint64(m.Coin))
	}
	if len(m.Name) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintGame(dAtA, i, uint64(len(m.Name)))
		i += copy(dAtA[i:], m.Name)
	}
	return i, nil
}

func encodeVarintGame(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *RoomInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovGame(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovGame(uint64(m.Id))
	}
	if m.Kind != 0 {
		n += 1 + sovGame(uint64(m.Kind))
	}
	if m.Level != 0 {
		n += 1 + sovGame(uint64(m.Level))
	}
	if m.Cap != 0 {
		n += 1 + sovGame(uint64(m.Cap))
	}
	if m.Ante != 0 {
		n += 1 + sovGame(uint64(m.Ante))
	}
	if m.DoorMin != 0 {
		n += 1 + sovGame(uint64(m.DoorMin))
	}
	if m.DoorMax != 0 {
		n += 1 + sovGame(uint64(m.DoorMax))
	}
	if m.StayMin != 0 {
		n += 1 + sovGame(uint64(m.StayMin))
	}
	if m.StayMax != 0 {
		n += 1 + sovGame(uint64(m.StayMax))
	}
	if m.PlayMin != 0 {
		n += 1 + sovGame(uint64(m.PlayMin))
	}
	if m.PlayMax != 0 {
		n += 1 + sovGame(uint64(m.PlayMax))
	}
	l = len(m.CoinKey)
	if l > 0 {
		n += 1 + l + sovGame(uint64(l))
	}
	if m.Icon != 0 {
		n += 1 + sovGame(uint64(m.Icon))
	}
	if m.Online != 0 {
		n += 1 + sovGame(uint64(m.Online))
	}
	return n
}

func (m *RoomListReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Kind != 0 {
		n += 1 + sovGame(uint64(m.Kind))
	}
	return n
}

func (m *RoomListAck) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Rooms) > 0 {
		for _, e := range m.Rooms {
			l = e.Size()
			n += 1 + l + sovGame(uint64(l))
		}
	}
	return n
}

func (m *LoginRoomReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovGame(uint64(m.Id))
	}
	l = len(m.Args)
	if l > 0 {
		n += 1 + l + sovGame(uint64(l))
	}
	return n
}

func (m *LoginRoomAck) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Kind != 0 {
		n += 1 + sovGame(uint64(m.Kind))
	}
	if m.Room != 0 {
		n += 1 + sovGame(uint64(m.Room))
	}
	if m.Tab != 0 {
		n += 1 + sovGame(uint64(m.Tab))
	}
	if m.Seat != 0 {
		n += 1 + sovGame(uint64(m.Seat))
	}
	if m.Code != 0 {
		n += 1 + sovGame(uint64(m.Code))
	}
	l = len(m.Msg)
	if l > 0 {
		n += 1 + l + sovGame(uint64(l))
	}
	return n
}

func (m *SendRoomFail) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Code != 0 {
		n += 1 + sovGame(uint64(m.Code))
	}
	l = len(m.Msg)
	if l > 0 {
		n += 1 + l + sovGame(uint64(l))
	}
	if m.Kind != 0 {
		n += 1 + sovGame(uint64(m.Kind))
	}
	if m.Room != 0 {
		n += 1 + sovGame(uint64(m.Room))
	}
	return n
}

func (m *User) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovGame(uint64(m.Id))
	}
	if m.Icon != 0 {
		n += 1 + sovGame(uint64(m.Icon))
	}
	if m.Vip != 0 {
		n += 1 + sovGame(uint64(m.Vip))
	}
	if m.Coin != 0 {
		n += 1 + sovGame(uint64(m.Coin))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovGame(uint64(l))
	}
	return n
}

func sovGame(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozGame(x uint64) (n int) {
	return sovGame(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *RoomInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGame
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RoomInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RoomInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGame
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGame
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Kind", wireType)
			}
			m.Kind = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Kind |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Level", wireType)
			}
			m.Level = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Level |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cap", wireType)
			}
			m.Cap = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Cap |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ante", wireType)
			}
			m.Ante = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Ante |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DoorMin", wireType)
			}
			m.DoorMin = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DoorMin |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DoorMax", wireType)
			}
			m.DoorMax = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DoorMax |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StayMin", wireType)
			}
			m.StayMin = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StayMin |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StayMax", wireType)
			}
			m.StayMax = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StayMax |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PlayMin", wireType)
			}
			m.PlayMin = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PlayMin |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PlayMax", wireType)
			}
			m.PlayMax = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PlayMax |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CoinKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGame
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGame
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CoinKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Icon", wireType)
			}
			m.Icon = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Icon |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Online", wireType)
			}
			m.Online = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Online |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGame(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGame
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthGame
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RoomListReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGame
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RoomListReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RoomListReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Kind", wireType)
			}
			m.Kind = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Kind |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGame(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGame
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthGame
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RoomListAck) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGame
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RoomListAck: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RoomListAck: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rooms", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGame
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGame
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Rooms = append(m.Rooms, &RoomInfo{})
			if err := m.Rooms[len(m.Rooms)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGame(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGame
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthGame
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LoginRoomReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGame
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LoginRoomReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LoginRoomReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Args", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGame
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGame
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Args = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGame(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGame
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthGame
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LoginRoomAck) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGame
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LoginRoomAck: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LoginRoomAck: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Kind", wireType)
			}
			m.Kind = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Kind |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Room", wireType)
			}
			m.Room = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Room |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tab", wireType)
			}
			m.Tab = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Tab |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Seat", wireType)
			}
			m.Seat = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Seat |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Code", wireType)
			}
			m.Code = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Code |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Msg", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGame
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGame
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Msg = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGame(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGame
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthGame
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SendRoomFail) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGame
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SendRoomFail: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SendRoomFail: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Code", wireType)
			}
			m.Code = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Code |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Msg", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGame
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGame
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Msg = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Kind", wireType)
			}
			m.Kind = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Kind |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Room", wireType)
			}
			m.Room = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Room |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGame(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGame
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthGame
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *User) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGame
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: User: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: User: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Icon", wireType)
			}
			m.Icon = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Icon |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vip", wireType)
			}
			m.Vip = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Vip |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Coin", wireType)
			}
			m.Coin = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Coin |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGame
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGame
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGame(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGame
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthGame
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGame(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGame
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGame
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGame
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGame
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthGame
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowGame
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipGame(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthGame
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthGame = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGame   = fmt.Errorf("proto: integer overflow")
)
