// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: msg_id.proto

//import "game.proto";

package msg

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type MsgId_Code int32

const (
	MsgId_Control             MsgId_Code = 0
	MsgId_HandshakeReq        MsgId_Code = 2
	MsgId_HandshakeAck        MsgId_Code = 3
	MsgId_VerCheckReq         MsgId_Code = 4
	MsgId_VerCheckAck         MsgId_Code = 5
	MsgId_RegistReq           MsgId_Code = 7
	MsgId_RegistAck           MsgId_Code = 8
	MsgId_ErrorInfo           MsgId_Code = 9
	MsgId_FatalInfo           MsgId_Code = 12
	MsgId_UserLoginReq        MsgId_Code = 13
	MsgId_UserLoginSuccessAck MsgId_Code = 15
	MsgId_UserLoginFailAck    MsgId_Code = 17
	MsgId_ClientErrorAck      MsgId_Code = 19
	MsgId_CodeLoginPwdReq     MsgId_Code = 20
	MsgId_CodeLoginPwdAck     MsgId_Code = 21
	// 100以上需要登录才能调用的协议
	MsgId_UserMessageHeadSplit MsgId_Code = 100
	MsgId_HeartBeatReq         MsgId_Code = 102
	MsgId_HeartBeatAck         MsgId_Code = 103
	MsgId_GameListReq          MsgId_Code = 104
	MsgId_GameListAck          MsgId_Code = 105
	MsgId_CodeUpAccountReq     MsgId_Code = 110
	MsgId_CodeUpAccountAck     MsgId_Code = 111
	MsgId_UpdateAccountReq     MsgId_Code = 112
	MsgId_UpdateAccountAck     MsgId_Code = 113
	MsgId_CodeSetPwdReq        MsgId_Code = 114
	MsgId_CodeSetPwdAck        MsgId_Code = 115
	MsgId_ChangePwdReq         MsgId_Code = 116
	MsgId_ChangePwdAck         MsgId_Code = 117
	MsgId_BagGetReq            MsgId_Code = 120
	MsgId_BagGetAck            MsgId_Code = 121
	MsgId_BagMoveReq           MsgId_Code = 122
	MsgId_BagMoveAck           MsgId_Code = 123
	MsgId_RepayInfoReq         MsgId_Code = 140
	MsgId_RepayInfoAck         MsgId_Code = 141
	MsgId_RepaySetAliReq       MsgId_Code = 142
	MsgId_RepaySetAliAck       MsgId_Code = 143
	MsgId_RepaySetBankReq      MsgId_Code = 144
	MsgId_RepaySetBankAck      MsgId_Code = 145
	MsgId_RepayListOrderReq    MsgId_Code = 146
	MsgId_RepayListOrderAck    MsgId_Code = 147
	MsgId_RepayNewOrderReq     MsgId_Code = 148
	MsgId_RepayNewOrderAck     MsgId_Code = 149
	MsgId_CustomSendReq        MsgId_Code = 160
	MsgId_CustomSendAck        MsgId_Code = 161
	MsgId_CustomRecvReq        MsgId_Code = 162
	MsgId_CustomRecvAck        MsgId_Code = 163
	MsgId_CustomCommonReq      MsgId_Code = 164
	MsgId_CustomCommonAck      MsgId_Code = 165
	MsgId_CustomNoteReq        MsgId_Code = 166
	MsgId_CustomNoteAck        MsgId_Code = 167
	MsgId_RankGetReq           MsgId_Code = 170
	MsgId_RankGetAck           MsgId_Code = 171
	MsgId_LoginRoomReq         MsgId_Code = 201
	MsgId_LoginRoomAck         MsgId_Code = 202
	MsgId_SendRoomFail         MsgId_Code = 204
	MsgId_PayInfoReq           MsgId_Code = 1100
	MsgId_PayInfoAck           MsgId_Code = 1101
	MsgId_PayOrderReq          MsgId_Code = 1102
	MsgId_PayOrderAck          MsgId_Code = 1103
	MsgId_MailListReq          MsgId_Code = 1110
	MsgId_MailListAck          MsgId_Code = 1111
	MsgId_MailReadReq          MsgId_Code = 1112
	MsgId_MailReadAck          MsgId_Code = 1113
	MsgId_MailDeleteReq        MsgId_Code = 1114
	MsgId_MailDeleteAck        MsgId_Code = 1115
	MsgId_SpreadGetReq         MsgId_Code = 1130
	MsgId_SpreadGetAck         MsgId_Code = 1131
	MsgId_SpreadSetReq         MsgId_Code = 1132
	MsgId_SpreadSetAck         MsgId_Code = 1133
	MsgId_SpreadGiftReq        MsgId_Code = 1134
	MsgId_SpreadGiftAck        MsgId_Code = 1135
	// 8192以上是游戏请求
	MsgId_GameMessageHeadSplit MsgId_Code = 8192
	MsgId_ReadyGameReq         MsgId_Code = 8193
	MsgId_ReadyGameAck         MsgId_Code = 8194
	MsgId_BetReq               MsgId_Code = 8201
	MsgId_BetAck               MsgId_Code = 8202
	MsgId_FolksGameInitAck     MsgId_Code = 8203
	MsgId_UserBetAck           MsgId_Code = 8204
	MsgId_OpenBetAck           MsgId_Code = 8205
	MsgId_CloseBetAck          MsgId_Code = 8206
)

var MsgId_Code_name = map[int32]string{
	0:    "Control",
	2:    "HandshakeReq",
	3:    "HandshakeAck",
	4:    "VerCheckReq",
	5:    "VerCheckAck",
	7:    "RegistReq",
	8:    "RegistAck",
	9:    "ErrorInfo",
	12:   "FatalInfo",
	13:   "UserLoginReq",
	15:   "UserLoginSuccessAck",
	17:   "UserLoginFailAck",
	19:   "ClientErrorAck",
	20:   "CodeLoginPwdReq",
	21:   "CodeLoginPwdAck",
	100:  "UserMessageHeadSplit",
	102:  "HeartBeatReq",
	103:  "HeartBeatAck",
	104:  "GameListReq",
	105:  "GameListAck",
	110:  "CodeUpAccountReq",
	111:  "CodeUpAccountAck",
	112:  "UpdateAccountReq",
	113:  "UpdateAccountAck",
	114:  "CodeSetPwdReq",
	115:  "CodeSetPwdAck",
	116:  "ChangePwdReq",
	117:  "ChangePwdAck",
	120:  "BagGetReq",
	121:  "BagGetAck",
	122:  "BagMoveReq",
	123:  "BagMoveAck",
	140:  "RepayInfoReq",
	141:  "RepayInfoAck",
	142:  "RepaySetAliReq",
	143:  "RepaySetAliAck",
	144:  "RepaySetBankReq",
	145:  "RepaySetBankAck",
	146:  "RepayListOrderReq",
	147:  "RepayListOrderAck",
	148:  "RepayNewOrderReq",
	149:  "RepayNewOrderAck",
	160:  "CustomSendReq",
	161:  "CustomSendAck",
	162:  "CustomRecvReq",
	163:  "CustomRecvAck",
	164:  "CustomCommonReq",
	165:  "CustomCommonAck",
	166:  "CustomNoteReq",
	167:  "CustomNoteAck",
	170:  "RankGetReq",
	171:  "RankGetAck",
	201:  "LoginRoomReq",
	202:  "LoginRoomAck",
	204:  "SendRoomFail",
	1100: "PayInfoReq",
	1101: "PayInfoAck",
	1102: "PayOrderReq",
	1103: "PayOrderAck",
	1110: "MailListReq",
	1111: "MailListAck",
	1112: "MailReadReq",
	1113: "MailReadAck",
	1114: "MailDeleteReq",
	1115: "MailDeleteAck",
	1130: "SpreadGetReq",
	1131: "SpreadGetAck",
	1132: "SpreadSetReq",
	1133: "SpreadSetAck",
	1134: "SpreadGiftReq",
	1135: "SpreadGiftAck",
	8192: "GameMessageHeadSplit",
	8193: "ReadyGameReq",
	8194: "ReadyGameAck",
	8201: "BetReq",
	8202: "BetAck",
	8203: "FolksGameInitAck",
	8204: "UserBetAck",
	8205: "OpenBetAck",
	8206: "CloseBetAck",
}

var MsgId_Code_value = map[string]int32{
	"Control":              0,
	"HandshakeReq":         2,
	"HandshakeAck":         3,
	"VerCheckReq":          4,
	"VerCheckAck":          5,
	"RegistReq":            7,
	"RegistAck":            8,
	"ErrorInfo":            9,
	"FatalInfo":            12,
	"UserLoginReq":         13,
	"UserLoginSuccessAck":  15,
	"UserLoginFailAck":     17,
	"ClientErrorAck":       19,
	"CodeLoginPwdReq":      20,
	"CodeLoginPwdAck":      21,
	"UserMessageHeadSplit": 100,
	"HeartBeatReq":         102,
	"HeartBeatAck":         103,
	"GameListReq":          104,
	"GameListAck":          105,
	"CodeUpAccountReq":     110,
	"CodeUpAccountAck":     111,
	"UpdateAccountReq":     112,
	"UpdateAccountAck":     113,
	"CodeSetPwdReq":        114,
	"CodeSetPwdAck":        115,
	"ChangePwdReq":         116,
	"ChangePwdAck":         117,
	"BagGetReq":            120,
	"BagGetAck":            121,
	"BagMoveReq":           122,
	"BagMoveAck":           123,
	"RepayInfoReq":         140,
	"RepayInfoAck":         141,
	"RepaySetAliReq":       142,
	"RepaySetAliAck":       143,
	"RepaySetBankReq":      144,
	"RepaySetBankAck":      145,
	"RepayListOrderReq":    146,
	"RepayListOrderAck":    147,
	"RepayNewOrderReq":     148,
	"RepayNewOrderAck":     149,
	"CustomSendReq":        160,
	"CustomSendAck":        161,
	"CustomRecvReq":        162,
	"CustomRecvAck":        163,
	"CustomCommonReq":      164,
	"CustomCommonAck":      165,
	"CustomNoteReq":        166,
	"CustomNoteAck":        167,
	"RankGetReq":           170,
	"RankGetAck":           171,
	"LoginRoomReq":         201,
	"LoginRoomAck":         202,
	"SendRoomFail":         204,
	"PayInfoReq":           1100,
	"PayInfoAck":           1101,
	"PayOrderReq":          1102,
	"PayOrderAck":          1103,
	"MailListReq":          1110,
	"MailListAck":          1111,
	"MailReadReq":          1112,
	"MailReadAck":          1113,
	"MailDeleteReq":        1114,
	"MailDeleteAck":        1115,
	"SpreadGetReq":         1130,
	"SpreadGetAck":         1131,
	"SpreadSetReq":         1132,
	"SpreadSetAck":         1133,
	"SpreadGiftReq":        1134,
	"SpreadGiftAck":        1135,
	"GameMessageHeadSplit": 8192,
	"ReadyGameReq":         8193,
	"ReadyGameAck":         8194,
	"BetReq":               8201,
	"BetAck":               8202,
	"FolksGameInitAck":     8203,
	"UserBetAck":           8204,
	"OpenBetAck":           8205,
	"CloseBetAck":          8206,
}

func (x MsgId_Code) String() string {
	return proto.EnumName(MsgId_Code_name, int32(x))
}

func (MsgId_Code) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_719e06d2e65a68c8, []int{0, 0}
}

type Error_Code int32

const (
	Error_None           Error_Code = 0
	Error_Success        Error_Code = 0
	Error_OK             Error_Code = 0
	Error_LoginRepeat    Error_Code = 1
	Error_LoginFail      Error_Code = 2
	Error_LoginOther     Error_Code = 3
	Error_CreateUserFail Error_Code = 4
	Error_DatabaseFail   Error_Code = 5
)

var Error_Code_name = map[int32]string{
	0: "None",
	// Duplicate value: 0: "Success",
	// Duplicate value: 0: "OK",
	1: "LoginRepeat",
	2: "LoginFail",
	3: "LoginOther",
	4: "CreateUserFail",
	5: "DatabaseFail",
}

var Error_Code_value = map[string]int32{
	"None":           0,
	"Success":        0,
	"OK":             0,
	"LoginRepeat":    1,
	"LoginFail":      2,
	"LoginOther":     3,
	"CreateUserFail": 4,
	"DatabaseFail":   5,
}

func (x Error_Code) String() string {
	return proto.EnumName(Error_Code_name, int32(x))
}

func (Error_Code) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_719e06d2e65a68c8, []int{1, 0}
}

type MsgId struct {
}

func (m *MsgId) Reset()         { *m = MsgId{} }
func (m *MsgId) String() string { return proto.CompactTextString(m) }
func (*MsgId) ProtoMessage()    {}
func (*MsgId) Descriptor() ([]byte, []int) {
	return fileDescriptor_719e06d2e65a68c8, []int{0}
}
func (m *MsgId) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgId.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgId.Merge(m, src)
}
func (m *MsgId) XXX_Size() int {
	return m.Size()
}
func (m *MsgId) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgId.DiscardUnknown(m)
}

var xxx_messageInfo_MsgId proto.InternalMessageInfo

type Error struct {
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_719e06d2e65a68c8, []int{1}
}
func (m *Error) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Error.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return m.Size()
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("msg.MsgId_Code", MsgId_Code_name, MsgId_Code_value)
	proto.RegisterEnum("msg.Error_Code", Error_Code_name, Error_Code_value)
	proto.RegisterType((*MsgId)(nil), "msg.MsgId")
	proto.RegisterType((*Error)(nil), "msg.Error")
}

func init() { proto.RegisterFile("msg_id.proto", fileDescriptor_719e06d2e65a68c8) }

var fileDescriptor_719e06d2e65a68c8 = []byte{
	// 846 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x95, 0xcb, 0x72, 0x1b, 0x45,
	0x14, 0x86, 0x35, 0xbe, 0x45, 0x69, 0xc9, 0x56, 0xbb, 0xad, 0x40, 0x60, 0xa1, 0x85, 0x1f, 0x80,
	0x0d, 0x2f, 0x20, 0x6b, 0x82, 0x13, 0x17, 0x91, 0xe5, 0x92, 0x2a, 0x6c, 0xa9, 0x8e, 0xe6, 0x78,
	0x34, 0xa5, 0xd1, 0xf4, 0x78, 0xa6, 0x95, 0x20, 0x58, 0x70, 0xd9, 0x70, 0x4b, 0x42, 0xb8, 0xed,
	0xb9, 0x53, 0x05, 0x2f, 0x02, 0x54, 0x80, 0xac, 0xc0, 0xc0, 0x86, 0xb2, 0x77, 0x5c, 0x9f, 0x80,
	0x2a, 0xea, 0x3f, 0x1a, 0xcb, 0x33, 0x52, 0x96, 0xfd, 0xf5, 0xd7, 0x67, 0xfa, 0x9c, 0xee, 0x3e,
	0x23, 0xaa, 0xa3, 0xd4, 0x7f, 0x3e, 0xf0, 0x9e, 0x8a, 0x13, 0x63, 0x8d, 0x5a, 0x1e, 0xa5, 0xfe,
	0xf6, 0xeb, 0x55, 0xb1, 0xda, 0x4e, 0xfd, 0x3d, 0x6f, 0xfb, 0xbf, 0x8a, 0x58, 0x71, 0x8d, 0x47,
	0xaa, 0x22, 0x2e, 0xb8, 0x26, 0xb2, 0x89, 0x09, 0x65, 0x49, 0x49, 0x51, 0xbd, 0xa6, 0x23, 0x2f,
	0x1d, 0xe8, 0x21, 0x75, 0xe9, 0x48, 0x2e, 0x15, 0xc8, 0x4e, 0x7f, 0x28, 0x97, 0x55, 0x4d, 0x54,
	0x9e, 0xa3, 0xc4, 0x1d, 0x50, 0x7f, 0x08, 0x65, 0x25, 0x0f, 0x60, 0xac, 0xaa, 0x75, 0x71, 0xb1,
	0x4b, 0x7e, 0x90, 0x5a, 0xcc, 0x5f, 0x38, 0x1f, 0x62, 0xb6, 0x8c, 0xe1, 0x33, 0x49, 0x62, 0x92,
	0xbd, 0xe8, 0xd0, 0xc8, 0x8b, 0x18, 0xee, 0x6a, 0xab, 0x43, 0x1e, 0x56, 0xf1, 0xbd, 0x1b, 0x29,
	0x25, 0xd7, 0x8d, 0x1f, 0x44, 0x58, 0xbe, 0xae, 0x1e, 0x17, 0x5b, 0x33, 0xd2, 0x1b, 0xf7, 0xfb,
	0x94, 0xa6, 0x08, 0x54, 0x53, 0x75, 0x21, 0x67, 0x13, 0xbb, 0x3a, 0x08, 0x41, 0x37, 0x95, 0x12,
	0x1b, 0x6e, 0x18, 0x50, 0x64, 0xf9, 0x23, 0x60, 0x5b, 0x6a, 0x4b, 0xd4, 0x90, 0x2b, 0x9b, 0x07,
	0xb7, 0x3d, 0xc4, 0xad, 0xcf, 0x43, 0x98, 0x97, 0xd4, 0x65, 0x51, 0x47, 0xcc, 0x36, 0xa5, 0xa9,
	0xf6, 0xe9, 0x1a, 0x69, 0xaf, 0x17, 0x87, 0x81, 0x95, 0x1e, 0x17, 0x82, 0x74, 0x62, 0x5b, 0xa4,
	0x39, 0xaf, 0xc3, 0x02, 0xc1, 0x6a, 0x1f, 0x95, 0xb8, 0xaa, 0x47, 0x74, 0x3d, 0x4b, 0x7d, 0x90,
	0x07, 0x30, 0x02, 0xec, 0x19, 0x1f, 0xbd, 0x11, 0xef, 0xf4, 0xfb, 0x66, 0x1c, 0xb1, 0x16, 0x2d,
	0x50, 0xb8, 0x86, 0xf3, 0x8b, 0x3d, 0x6d, 0x29, 0xe7, 0xc6, 0x0b, 0x14, 0xee, 0x91, 0xda, 0x14,
	0xeb, 0x88, 0xd0, 0x23, 0x9b, 0xe5, 0x97, 0x14, 0x11, 0xac, 0x14, 0x3b, 0x76, 0x07, 0x3a, 0xf2,
	0x29, 0x93, 0x6c, 0x81, 0xc0, 0x19, 0xe3, 0x3c, 0x5a, 0xda, 0xbf, 0x4a, 0xfc, 0xb9, 0x17, 0xce,
	0x87, 0x98, 0x9d, 0xa8, 0x0d, 0x21, 0x5a, 0xda, 0x6f, 0x9b, 0x5b, 0x7c, 0x3d, 0x5e, 0xcc, 0x8d,
	0x31, 0xff, 0x92, 0xda, 0x14, 0xd5, 0x2e, 0xc5, 0x7a, 0x82, 0xd3, 0x84, 0x71, 0xc7, 0x29, 0x20,
	0x48, 0x77, 0x1d, 0xb5, 0x25, 0x36, 0x18, 0xf5, 0xc8, 0xee, 0x84, 0x01, 0xbc, 0x7b, 0xf3, 0x10,
	0xe6, 0x3b, 0x8e, 0xaa, 0x8b, 0xda, 0x19, 0x6c, 0xe9, 0x88, 0x2f, 0xdc, 0xfd, 0x05, 0x0a, 0xf7,
	0x5d, 0x47, 0x3d, 0x26, 0x36, 0x99, 0xa2, 0xda, 0x9d, 0xc4, 0xa3, 0x04, 0xf6, 0x7b, 0x8f, 0xe0,
	0xf0, 0xdf, 0x77, 0xd4, 0x25, 0x21, 0x99, 0xef, 0xd3, 0xed, 0x99, 0xfe, 0xc1, 0x22, 0x86, 0xfd,
	0xa1, 0xa3, 0x94, 0x58, 0x77, 0xc7, 0xa9, 0x35, 0xa3, 0x1e, 0x45, 0x5c, 0xbc, 0x8f, 0xe6, 0x18,
	0xbc, 0x8f, 0x73, 0xac, 0x4b, 0xfd, 0x5b, 0xf0, 0x3e, 0x99, 0x63, 0xf0, 0x3e, 0xe5, 0x1c, 0xa6,
	0xcc, 0x35, 0xa3, 0x91, 0xe1, 0xbb, 0xfe, 0xd9, 0x02, 0x85, 0xfb, 0x79, 0x6e, 0xfd, 0xbe, 0xb1,
	0x5c, 0xf8, 0x2f, 0xe6, 0x18, 0xbc, 0x2f, 0x1d, 0x55, 0x13, 0xa2, 0xab, 0xa3, 0x61, 0x76, 0x78,
	0x5f, 0xe5, 0x01, 0x8c, 0xaf, 0xf9, 0x30, 0xa6, 0x4f, 0xcb, 0x60, 0x33, 0x47, 0xf2, 0xdb, 0x22,
	0x82, 0xf5, 0x1d, 0x23, 0xce, 0xd2, 0x98, 0x11, 0x1e, 0x96, 0x7c, 0xc0, 0x91, 0x0e, 0xce, 0x8f,
	0xf5, 0x41, 0x39, 0x07, 0xb0, 0xe8, 0xfb, 0xb2, 0x92, 0xa2, 0x72, 0xa0, 0x27, 0xb3, 0x4a, 0xfe,
	0x50, 0x20, 0x70, 0x7e, 0x64, 0xd2, 0xd6, 0x41, 0x78, 0xf6, 0x40, 0x7e, 0x2a, 0x10, 0x38, 0x3f,
	0xcf, 0x48, 0x97, 0x34, 0x97, 0xf9, 0xb8, 0x40, 0xe0, 0xfc, 0x52, 0x46, 0xf2, 0x20, 0x57, 0x28,
	0xa4, 0x69, 0x41, 0x7e, 0x9d, 0x63, 0xf0, 0x7e, 0x2b, 0x73, 0x22, 0x71, 0x42, 0xda, 0xcb, 0x4a,
	0xf2, 0x47, 0x11, 0xc1, 0xfa, 0x33, 0x87, 0x7a, 0x53, 0xeb, 0xaf, 0x22, 0x82, 0xf5, 0x37, 0xc7,
	0xcf, 0x16, 0x06, 0x87, 0xac, 0xfd, 0x33, 0xc7, 0xe0, 0xfd, 0x5b, 0x56, 0x4f, 0x88, 0x3a, 0xde,
	0xfc, 0x42, 0x0b, 0x79, 0xa5, 0x39, 0x7d, 0x0a, 0xda, 0x9b, 0x60, 0x1e, 0x11, 0x5e, 0x2d, 0x22,
	0x04, 0x78, 0xad, 0xa9, 0x2a, 0x62, 0xad, 0x35, 0xdd, 0xc8, 0x9b, 0x67, 0x03, 0xcc, 0xbc, 0xd5,
	0xc4, 0xd5, 0xdc, 0x35, 0xe1, 0x30, 0x85, 0xbc, 0x17, 0x05, 0x8c, 0xdf, 0x6e, 0xe2, 0x28, 0xd0,
	0xb4, 0x32, 0xef, 0x0e, 0x83, 0x4e, 0x4c, 0x51, 0x06, 0xee, 0x36, 0x51, 0x41, 0x37, 0x34, 0x29,
	0x65, 0xe4, 0x5e, 0x73, 0xfb, 0x0d, 0x47, 0xac, 0x72, 0x87, 0xdc, 0x7e, 0x39, 0xfb, 0x11, 0x94,
	0xc5, 0xca, 0xbe, 0x89, 0x48, 0x96, 0xf0, 0x4b, 0xc8, 0x1a, 0xad, 0x2c, 0xa9, 0x35, 0xb1, 0xd4,
	0x79, 0x56, 0x96, 0xd0, 0xca, 0xb2, 0xa6, 0x1c, 0x93, 0xb6, 0xd2, 0x41, 0x67, 0x98, 0xb5, 0x5e,
	0xb9, 0x84, 0x4e, 0xc0, 0xc3, 0x8e, 0x1d, 0x50, 0x22, 0x97, 0xb9, 0x0f, 0x27, 0xa4, 0x2d, 0x61,
	0x6b, 0xec, 0xac, 0xa0, 0xdb, 0x5c, 0xd1, 0x56, 0xdf, 0xd4, 0x29, 0x31, 0x59, 0x7d, 0x72, 0x49,
	0x3a, 0xad, 0xcb, 0xdf, 0x9c, 0x34, 0x9c, 0x87, 0x27, 0x0d, 0xe7, 0xf7, 0x93, 0x86, 0x73, 0xff,
	0xb4, 0x51, 0x7a, 0x78, 0xda, 0x28, 0x1d, 0x9f, 0x36, 0x4a, 0x37, 0xd7, 0xf8, 0xd7, 0xf5, 0xf4,
	0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x2a, 0xf9, 0x69, 0x8e, 0xca, 0x06, 0x00, 0x00,
}

func (m *MsgId) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgId) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func (m *Error) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Error) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func encodeVarintMsgId(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *MsgId) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *Error) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovMsgId(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozMsgId(x uint64) (n int) {
	return sovMsgId(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgId) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgId
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgId: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgId: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipMsgId(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMsgId
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthMsgId
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Error) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgId
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Error: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Error: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipMsgId(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMsgId
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthMsgId
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMsgId(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMsgId
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgId
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgId
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMsgId
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthMsgId
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowMsgId
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipMsgId(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthMsgId
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthMsgId = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMsgId   = fmt.Errorf("proto: integer overflow")
)
