consul:
  addr: '127.0.0.1:8500'
  #consul service prefix
  serverPrefix: s
  #room service prefix
  roomPrefix: r
  #ttl(second)
  ttl: 15

grpc:
  listen: '0.0.0.0:27001'
  addr: '127.0.0.1'
  port: 27001
  name: 'x.27001'
  dcsa: 5
  interval: 5
  tags: []
  maxConnect: 1000

tcp:
  listen: '0.0.0.0:27001'
  readBuf: 1048576
  writeBuf: 1048576

database:
  driver: 'mongodb'
  url3: 'mongodb://localhost:27088'
  url: 'mongodb://127.0.0.1:27088,127.0.0.1:27089,127.0.0.1:27090/admin?replicaSet=gameRs'
  name: 'game'
  watch: ['-appConf','-packConf','-chanConf','-hintConf','-roomConf']
  refresh:
    appConf: 5
    packConf: 5
    chanConf: 5
    hintConf: 30
    roomConf: 60

#消息编码
codec: msg
#per connection read timeout(second)
readTimeout: 15
#per connection output message queue, packet will be dropped if exceeds
outChanLen: 128
#per connection in message queue, packet will be dropped if exceeds
inChanLen: 128
#max connect number limit
maxConnect: 4000
#per connection rpm limit
rpmLimit: 200

#http://localhost:6060/debug/pprof
pprof: '0.0.0.0:6060'

#log level: debug/info/warn/error/fatal/panic
logLevel: 'debug'
logFile: ''

room:
  #28001,27001
  id: 27001
  #280,270
  kind: 270
  addr: '127.0.0.1:50001'
  key: 'fdf843JJE'




