go build github.com/gogo/protobuf/protoc-gen-combo
go build github.com/gogo/protobuf/protoc-gen-gofast
go build github.com/gogo/protobuf/protoc-gen-gogo
go build github.com/gogo/protobuf/protoc-gen-gogofast
go build github.com/gogo/protobuf/protoc-gen-gogofaster
go build github.com/gogo/protobuf/protoc-gen-gogoslick
go build github.com/gogo/protobuf/protoc-gen-gogotypes
go build github.com/gogo/protobuf/protoc-gen-gostring
go build github.com/golang/protobuf/protoc-gen-go
go build github.com/tinylib/msgp
go build github.com/ugorji/go/codec/codecgen