package protocol

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	_ "github.com/gogo/protobuf/gogoproto"
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *ExitGameAck) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "code":
			z.Code, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "Code")
				return
			}
		case "msg":
			z.Msg, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Msg")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z ExitGameAck) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "code"
	err = en.Append(0x82, 0xa4, 0x63, 0x6f, 0x64, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.Code)
	if err != nil {
		err = msgp.WrapError(err, "Code")
		return
	}
	// write "msg"
	err = en.Append(0xa3, 0x6d, 0x73, 0x67)
	if err != nil {
		return
	}
	err = en.WriteString(z.Msg)
	if err != nil {
		err = msgp.WrapError(err, "Msg")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z ExitGameAck) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "code"
	o = append(o, 0x82, 0xa4, 0x63, 0x6f, 0x64, 0x65)
	o = msgp.AppendInt32(o, z.Code)
	// string "msg"
	o = append(o, 0xa3, 0x6d, 0x73, 0x67)
	o = msgp.AppendString(o, z.Msg)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *ExitGameAck) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "code":
			z.Code, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Code")
				return
			}
		case "msg":
			z.Msg, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Msg")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z ExitGameAck) Msgsize() (s int) {
	s = 1 + 5 + msgp.Int32Size + 4 + msgp.StringPrefixSize + len(z.Msg)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *ExitGameReq) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "game":
			z.Game, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "Game")
				return
			}
		case "room":
			z.Room, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "Room")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z ExitGameReq) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "game"
	err = en.Append(0x82, 0xa4, 0x67, 0x61, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.Game)
	if err != nil {
		err = msgp.WrapError(err, "Game")
		return
	}
	// write "room"
	err = en.Append(0xa4, 0x72, 0x6f, 0x6f, 0x6d)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.Room)
	if err != nil {
		err = msgp.WrapError(err, "Room")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z ExitGameReq) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "game"
	o = append(o, 0x82, 0xa4, 0x67, 0x61, 0x6d, 0x65)
	o = msgp.AppendInt32(o, z.Game)
	// string "room"
	o = append(o, 0xa4, 0x72, 0x6f, 0x6f, 0x6d)
	o = msgp.AppendInt32(o, z.Room)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *ExitGameReq) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "game":
			z.Game, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Game")
				return
			}
		case "room":
			z.Room, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Room")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z ExitGameReq) Msgsize() (s int) {
	s = 1 + 5 + msgp.Int32Size + 5 + msgp.Int32Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *GameKindAck) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "rooms":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Rooms")
				return
			}
			if cap(z.Rooms) >= int(zb0002) {
				z.Rooms = (z.Rooms)[:zb0002]
			} else {
				z.Rooms = make([]*RoomInfo, zb0002)
			}
			for za0001 := range z.Rooms {
				if dc.IsNil() {
					err = dc.ReadNil()
					if err != nil {
						err = msgp.WrapError(err, "Rooms", za0001)
						return
					}
					z.Rooms[za0001] = nil
				} else {
					if z.Rooms[za0001] == nil {
						z.Rooms[za0001] = new(RoomInfo)
					}
					err = z.Rooms[za0001].DecodeMsg(dc)
					if err != nil {
						err = msgp.WrapError(err, "Rooms", za0001)
						return
					}
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *GameKindAck) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 1
	// write "rooms"
	err = en.Append(0x81, 0xa5, 0x72, 0x6f, 0x6f, 0x6d, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Rooms)))
	if err != nil {
		err = msgp.WrapError(err, "Rooms")
		return
	}
	for za0001 := range z.Rooms {
		if z.Rooms[za0001] == nil {
			err = en.WriteNil()
			if err != nil {
				return
			}
		} else {
			err = z.Rooms[za0001].EncodeMsg(en)
			if err != nil {
				err = msgp.WrapError(err, "Rooms", za0001)
				return
			}
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *GameKindAck) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 1
	// string "rooms"
	o = append(o, 0x81, 0xa5, 0x72, 0x6f, 0x6f, 0x6d, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Rooms)))
	for za0001 := range z.Rooms {
		if z.Rooms[za0001] == nil {
			o = msgp.AppendNil(o)
		} else {
			o, err = z.Rooms[za0001].MarshalMsg(o)
			if err != nil {
				err = msgp.WrapError(err, "Rooms", za0001)
				return
			}
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *GameKindAck) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "rooms":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Rooms")
				return
			}
			if cap(z.Rooms) >= int(zb0002) {
				z.Rooms = (z.Rooms)[:zb0002]
			} else {
				z.Rooms = make([]*RoomInfo, zb0002)
			}
			for za0001 := range z.Rooms {
				if msgp.IsNil(bts) {
					bts, err = msgp.ReadNilBytes(bts)
					if err != nil {
						return
					}
					z.Rooms[za0001] = nil
				} else {
					if z.Rooms[za0001] == nil {
						z.Rooms[za0001] = new(RoomInfo)
					}
					bts, err = z.Rooms[za0001].UnmarshalMsg(bts)
					if err != nil {
						err = msgp.WrapError(err, "Rooms", za0001)
						return
					}
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *GameKindAck) Msgsize() (s int) {
	s = 1 + 6 + msgp.ArrayHeaderSize
	for za0001 := range z.Rooms {
		if z.Rooms[za0001] == nil {
			s += msgp.NilSize
		} else {
			s += z.Rooms[za0001].Msgsize()
		}
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *GameKindReq) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "game":
			z.Game, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "Game")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z GameKindReq) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 1
	// write "game"
	err = en.Append(0x81, 0xa4, 0x67, 0x61, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.Game)
	if err != nil {
		err = msgp.WrapError(err, "Game")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z GameKindReq) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 1
	// string "game"
	o = append(o, 0x81, 0xa4, 0x67, 0x61, 0x6d, 0x65)
	o = msgp.AppendInt32(o, z.Game)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *GameKindReq) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "game":
			z.Game, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Game")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z GameKindReq) Msgsize() (s int) {
	s = 1 + 5 + msgp.Int32Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *LoginGameAck) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "game":
			z.Game, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "Game")
				return
			}
		case "room":
			z.Room, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "Room")
				return
			}
		case "code":
			z.Code, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "Code")
				return
			}
		case "msg":
			z.Msg, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Msg")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *LoginGameAck) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 4
	// write "game"
	err = en.Append(0x84, 0xa4, 0x67, 0x61, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.Game)
	if err != nil {
		err = msgp.WrapError(err, "Game")
		return
	}
	// write "room"
	err = en.Append(0xa4, 0x72, 0x6f, 0x6f, 0x6d)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.Room)
	if err != nil {
		err = msgp.WrapError(err, "Room")
		return
	}
	// write "code"
	err = en.Append(0xa4, 0x63, 0x6f, 0x64, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.Code)
	if err != nil {
		err = msgp.WrapError(err, "Code")
		return
	}
	// write "msg"
	err = en.Append(0xa3, 0x6d, 0x73, 0x67)
	if err != nil {
		return
	}
	err = en.WriteString(z.Msg)
	if err != nil {
		err = msgp.WrapError(err, "Msg")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *LoginGameAck) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 4
	// string "game"
	o = append(o, 0x84, 0xa4, 0x67, 0x61, 0x6d, 0x65)
	o = msgp.AppendInt32(o, z.Game)
	// string "room"
	o = append(o, 0xa4, 0x72, 0x6f, 0x6f, 0x6d)
	o = msgp.AppendInt32(o, z.Room)
	// string "code"
	o = append(o, 0xa4, 0x63, 0x6f, 0x64, 0x65)
	o = msgp.AppendInt32(o, z.Code)
	// string "msg"
	o = append(o, 0xa3, 0x6d, 0x73, 0x67)
	o = msgp.AppendString(o, z.Msg)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *LoginGameAck) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "game":
			z.Game, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Game")
				return
			}
		case "room":
			z.Room, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Room")
				return
			}
		case "code":
			z.Code, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Code")
				return
			}
		case "msg":
			z.Msg, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Msg")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *LoginGameAck) Msgsize() (s int) {
	s = 1 + 5 + msgp.Int32Size + 5 + msgp.Int32Size + 5 + msgp.Int32Size + 4 + msgp.StringPrefixSize + len(z.Msg)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *LoginGameReq) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "game":
			z.Game, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "Game")
				return
			}
		case "level":
			z.Level, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "Level")
				return
			}
		case "room":
			z.Room, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "Room")
				return
			}
		case "args":
			z.Args, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Args")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *LoginGameReq) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 4
	// write "game"
	err = en.Append(0x84, 0xa4, 0x67, 0x61, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.Game)
	if err != nil {
		err = msgp.WrapError(err, "Game")
		return
	}
	// write "level"
	err = en.Append(0xa5, 0x6c, 0x65, 0x76, 0x65, 0x6c)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.Level)
	if err != nil {
		err = msgp.WrapError(err, "Level")
		return
	}
	// write "room"
	err = en.Append(0xa4, 0x72, 0x6f, 0x6f, 0x6d)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.Room)
	if err != nil {
		err = msgp.WrapError(err, "Room")
		return
	}
	// write "args"
	err = en.Append(0xa4, 0x61, 0x72, 0x67, 0x73)
	if err != nil {
		return
	}
	err = en.WriteString(z.Args)
	if err != nil {
		err = msgp.WrapError(err, "Args")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *LoginGameReq) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 4
	// string "game"
	o = append(o, 0x84, 0xa4, 0x67, 0x61, 0x6d, 0x65)
	o = msgp.AppendInt32(o, z.Game)
	// string "level"
	o = append(o, 0xa5, 0x6c, 0x65, 0x76, 0x65, 0x6c)
	o = msgp.AppendInt32(o, z.Level)
	// string "room"
	o = append(o, 0xa4, 0x72, 0x6f, 0x6f, 0x6d)
	o = msgp.AppendInt32(o, z.Room)
	// string "args"
	o = append(o, 0xa4, 0x61, 0x72, 0x67, 0x73)
	o = msgp.AppendString(o, z.Args)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *LoginGameReq) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "game":
			z.Game, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Game")
				return
			}
		case "level":
			z.Level, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Level")
				return
			}
		case "room":
			z.Room, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Room")
				return
			}
		case "args":
			z.Args, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Args")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *LoginGameReq) Msgsize() (s int) {
	s = 1 + 5 + msgp.Int32Size + 6 + msgp.Int32Size + 5 + msgp.Int32Size + 5 + msgp.StringPrefixSize + len(z.Args)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *RoomInfo) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "name":
			z.Name, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Name")
				return
			}
		case "id":
			z.Id, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "Id")
				return
			}
		case "game":
			z.Game, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "Game")
				return
			}
		case "level":
			z.Level, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "Level")
				return
			}
		case "cap":
			z.Cap, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "Cap")
				return
			}
		case "ante":
			z.Ante, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "Ante")
				return
			}
		case "doorMin":
			z.DoorMin, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "DoorMin")
				return
			}
		case "doorMax":
			z.DoorMax, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "DoorMax")
				return
			}
		case "stayMin":
			z.StayMin, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "StayMin")
				return
			}
		case "stayMax":
			z.StayMax, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "StayMax")
				return
			}
		case "playMin":
			z.PlayMin, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "PlayMin")
				return
			}
		case "playMax":
			z.PlayMax, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "PlayMax")
				return
			}
		case "coinKey":
			z.CoinKey, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "CoinKey")
				return
			}
		case "icon":
			z.Icon, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "Icon")
				return
			}
		case "online":
			z.Online, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "Online")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *RoomInfo) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 15
	// write "name"
	err = en.Append(0x8f, 0xa4, 0x6e, 0x61, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Name)
	if err != nil {
		err = msgp.WrapError(err, "Name")
		return
	}
	// write "id"
	err = en.Append(0xa2, 0x69, 0x64)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.Id)
	if err != nil {
		err = msgp.WrapError(err, "Id")
		return
	}
	// write "game"
	err = en.Append(0xa4, 0x67, 0x61, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.Game)
	if err != nil {
		err = msgp.WrapError(err, "Game")
		return
	}
	// write "level"
	err = en.Append(0xa5, 0x6c, 0x65, 0x76, 0x65, 0x6c)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.Level)
	if err != nil {
		err = msgp.WrapError(err, "Level")
		return
	}
	// write "cap"
	err = en.Append(0xa3, 0x63, 0x61, 0x70)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.Cap)
	if err != nil {
		err = msgp.WrapError(err, "Cap")
		return
	}
	// write "ante"
	err = en.Append(0xa4, 0x61, 0x6e, 0x74, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.Ante)
	if err != nil {
		err = msgp.WrapError(err, "Ante")
		return
	}
	// write "doorMin"
	err = en.Append(0xa7, 0x64, 0x6f, 0x6f, 0x72, 0x4d, 0x69, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.DoorMin)
	if err != nil {
		err = msgp.WrapError(err, "DoorMin")
		return
	}
	// write "doorMax"
	err = en.Append(0xa7, 0x64, 0x6f, 0x6f, 0x72, 0x4d, 0x61, 0x78)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.DoorMax)
	if err != nil {
		err = msgp.WrapError(err, "DoorMax")
		return
	}
	// write "stayMin"
	err = en.Append(0xa7, 0x73, 0x74, 0x61, 0x79, 0x4d, 0x69, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.StayMin)
	if err != nil {
		err = msgp.WrapError(err, "StayMin")
		return
	}
	// write "stayMax"
	err = en.Append(0xa7, 0x73, 0x74, 0x61, 0x79, 0x4d, 0x61, 0x78)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.StayMax)
	if err != nil {
		err = msgp.WrapError(err, "StayMax")
		return
	}
	// write "playMin"
	err = en.Append(0xa7, 0x70, 0x6c, 0x61, 0x79, 0x4d, 0x69, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.PlayMin)
	if err != nil {
		err = msgp.WrapError(err, "PlayMin")
		return
	}
	// write "playMax"
	err = en.Append(0xa7, 0x70, 0x6c, 0x61, 0x79, 0x4d, 0x61, 0x78)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.PlayMax)
	if err != nil {
		err = msgp.WrapError(err, "PlayMax")
		return
	}
	// write "coinKey"
	err = en.Append(0xa7, 0x63, 0x6f, 0x69, 0x6e, 0x4b, 0x65, 0x79)
	if err != nil {
		return
	}
	err = en.WriteString(z.CoinKey)
	if err != nil {
		err = msgp.WrapError(err, "CoinKey")
		return
	}
	// write "icon"
	err = en.Append(0xa4, 0x69, 0x63, 0x6f, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.Icon)
	if err != nil {
		err = msgp.WrapError(err, "Icon")
		return
	}
	// write "online"
	err = en.Append(0xa6, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.Online)
	if err != nil {
		err = msgp.WrapError(err, "Online")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *RoomInfo) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 15
	// string "name"
	o = append(o, 0x8f, 0xa4, 0x6e, 0x61, 0x6d, 0x65)
	o = msgp.AppendString(o, z.Name)
	// string "id"
	o = append(o, 0xa2, 0x69, 0x64)
	o = msgp.AppendInt32(o, z.Id)
	// string "game"
	o = append(o, 0xa4, 0x67, 0x61, 0x6d, 0x65)
	o = msgp.AppendInt32(o, z.Game)
	// string "level"
	o = append(o, 0xa5, 0x6c, 0x65, 0x76, 0x65, 0x6c)
	o = msgp.AppendInt32(o, z.Level)
	// string "cap"
	o = append(o, 0xa3, 0x63, 0x61, 0x70)
	o = msgp.AppendInt32(o, z.Cap)
	// string "ante"
	o = append(o, 0xa4, 0x61, 0x6e, 0x74, 0x65)
	o = msgp.AppendInt64(o, z.Ante)
	// string "doorMin"
	o = append(o, 0xa7, 0x64, 0x6f, 0x6f, 0x72, 0x4d, 0x69, 0x6e)
	o = msgp.AppendInt64(o, z.DoorMin)
	// string "doorMax"
	o = append(o, 0xa7, 0x64, 0x6f, 0x6f, 0x72, 0x4d, 0x61, 0x78)
	o = msgp.AppendInt64(o, z.DoorMax)
	// string "stayMin"
	o = append(o, 0xa7, 0x73, 0x74, 0x61, 0x79, 0x4d, 0x69, 0x6e)
	o = msgp.AppendInt64(o, z.StayMin)
	// string "stayMax"
	o = append(o, 0xa7, 0x73, 0x74, 0x61, 0x79, 0x4d, 0x61, 0x78)
	o = msgp.AppendInt64(o, z.StayMax)
	// string "playMin"
	o = append(o, 0xa7, 0x70, 0x6c, 0x61, 0x79, 0x4d, 0x69, 0x6e)
	o = msgp.AppendInt64(o, z.PlayMin)
	// string "playMax"
	o = append(o, 0xa7, 0x70, 0x6c, 0x61, 0x79, 0x4d, 0x61, 0x78)
	o = msgp.AppendInt64(o, z.PlayMax)
	// string "coinKey"
	o = append(o, 0xa7, 0x63, 0x6f, 0x69, 0x6e, 0x4b, 0x65, 0x79)
	o = msgp.AppendString(o, z.CoinKey)
	// string "icon"
	o = append(o, 0xa4, 0x69, 0x63, 0x6f, 0x6e)
	o = msgp.AppendInt32(o, z.Icon)
	// string "online"
	o = append(o, 0xa6, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65)
	o = msgp.AppendInt32(o, z.Online)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *RoomInfo) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "name":
			z.Name, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Name")
				return
			}
		case "id":
			z.Id, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Id")
				return
			}
		case "game":
			z.Game, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Game")
				return
			}
		case "level":
			z.Level, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Level")
				return
			}
		case "cap":
			z.Cap, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Cap")
				return
			}
		case "ante":
			z.Ante, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Ante")
				return
			}
		case "doorMin":
			z.DoorMin, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "DoorMin")
				return
			}
		case "doorMax":
			z.DoorMax, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "DoorMax")
				return
			}
		case "stayMin":
			z.StayMin, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "StayMin")
				return
			}
		case "stayMax":
			z.StayMax, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "StayMax")
				return
			}
		case "playMin":
			z.PlayMin, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "PlayMin")
				return
			}
		case "playMax":
			z.PlayMax, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "PlayMax")
				return
			}
		case "coinKey":
			z.CoinKey, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "CoinKey")
				return
			}
		case "icon":
			z.Icon, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Icon")
				return
			}
		case "online":
			z.Online, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Online")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *RoomInfo) Msgsize() (s int) {
	s = 1 + 5 + msgp.StringPrefixSize + len(z.Name) + 3 + msgp.Int32Size + 5 + msgp.Int32Size + 6 + msgp.Int32Size + 4 + msgp.Int32Size + 5 + msgp.Int64Size + 8 + msgp.Int64Size + 8 + msgp.Int64Size + 8 + msgp.Int64Size + 8 + msgp.Int64Size + 8 + msgp.Int64Size + 8 + msgp.Int64Size + 8 + msgp.StringPrefixSize + len(z.CoinKey) + 5 + msgp.Int32Size + 7 + msgp.Int32Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *SendGameFail) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "code":
			z.Code, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "Code")
				return
			}
		case "msg":
			z.Msg, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Msg")
				return
			}
		case "game":
			z.Game, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "Game")
				return
			}
		case "room":
			z.Room, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "Room")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *SendGameFail) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 4
	// write "code"
	err = en.Append(0x84, 0xa4, 0x63, 0x6f, 0x64, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.Code)
	if err != nil {
		err = msgp.WrapError(err, "Code")
		return
	}
	// write "msg"
	err = en.Append(0xa3, 0x6d, 0x73, 0x67)
	if err != nil {
		return
	}
	err = en.WriteString(z.Msg)
	if err != nil {
		err = msgp.WrapError(err, "Msg")
		return
	}
	// write "game"
	err = en.Append(0xa4, 0x67, 0x61, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.Game)
	if err != nil {
		err = msgp.WrapError(err, "Game")
		return
	}
	// write "room"
	err = en.Append(0xa4, 0x72, 0x6f, 0x6f, 0x6d)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.Room)
	if err != nil {
		err = msgp.WrapError(err, "Room")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *SendGameFail) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 4
	// string "code"
	o = append(o, 0x84, 0xa4, 0x63, 0x6f, 0x64, 0x65)
	o = msgp.AppendInt32(o, z.Code)
	// string "msg"
	o = append(o, 0xa3, 0x6d, 0x73, 0x67)
	o = msgp.AppendString(o, z.Msg)
	// string "game"
	o = append(o, 0xa4, 0x67, 0x61, 0x6d, 0x65)
	o = msgp.AppendInt32(o, z.Game)
	// string "room"
	o = append(o, 0xa4, 0x72, 0x6f, 0x6f, 0x6d)
	o = msgp.AppendInt32(o, z.Room)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *SendGameFail) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "code":
			z.Code, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Code")
				return
			}
		case "msg":
			z.Msg, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Msg")
				return
			}
		case "game":
			z.Game, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Game")
				return
			}
		case "room":
			z.Room, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Room")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *SendGameFail) Msgsize() (s int) {
	s = 1 + 5 + msgp.Int32Size + 4 + msgp.StringPrefixSize + len(z.Msg) + 5 + msgp.Int32Size + 5 + msgp.Int32Size
	return
}
