msgp.exe --file ../login.pb.go
msgp.exe --file ../game.pb.go
msgp.exe --file ../coin_flow.go
msgp.exe --file ../folks/folks.pb.go
msgp.exe --file ../folks/folks_log.pb.go
msgp.exe --file ../zjh/zjh.pb.go
msgp.exe --file ../zjh/zjh_log.pb.go
msgp.exe --file ../fish/fish.pb.go
msgp.exe --file ../fish/fish_log.pb.go