package zjh

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	_ "github.com/gogo/protobuf/gogoproto"
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *ActionAck) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Type":
			{
				var zb0002 int32
				zb0002, err = dc.ReadInt32()
				if err != nil {
					err = msgp.WrapError(err, "Type")
					return
				}
				z.Type = ActionType(zb0002)
			}
		case "Poker":
			z.Poker, err = dc.ReadBytes(z.Poker)
			if err != nil {
				err = msgp.WrapError(err, "Poker")
				return
			}
		case "Uid":
			z.Uid, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "Uid")
				return
			}
		case "Bet":
			z.Bet, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "Bet")
				return
			}
		case "Players":
			var zb0003 uint32
			zb0003, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Players")
				return
			}
			if cap(z.Players) >= int(zb0003) {
				z.Players = (z.Players)[:zb0003]
			} else {
				z.Players = make([]int32, zb0003)
			}
			for za0001 := range z.Players {
				z.Players[za0001], err = dc.ReadInt32()
				if err != nil {
					err = msgp.WrapError(err, "Players", za0001)
					return
				}
			}
		case "Winners":
			var zb0004 uint32
			zb0004, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Winners")
				return
			}
			if cap(z.Winners) >= int(zb0004) {
				z.Winners = (z.Winners)[:zb0004]
			} else {
				z.Winners = make([]int32, zb0004)
			}
			for za0002 := range z.Winners {
				z.Winners[za0002], err = dc.ReadInt32()
				if err != nil {
					err = msgp.WrapError(err, "Winners", za0002)
					return
				}
			}
		case "Coin":
			z.Coin, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "Coin")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *ActionAck) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 7
	// write "Type"
	err = en.Append(0x87, 0xa4, 0x54, 0x79, 0x70, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt32(int32(z.Type))
	if err != nil {
		err = msgp.WrapError(err, "Type")
		return
	}
	// write "Poker"
	err = en.Append(0xa5, 0x50, 0x6f, 0x6b, 0x65, 0x72)
	if err != nil {
		return
	}
	err = en.WriteBytes(z.Poker)
	if err != nil {
		err = msgp.WrapError(err, "Poker")
		return
	}
	// write "Uid"
	err = en.Append(0xa3, 0x55, 0x69, 0x64)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.Uid)
	if err != nil {
		err = msgp.WrapError(err, "Uid")
		return
	}
	// write "Bet"
	err = en.Append(0xa3, 0x42, 0x65, 0x74)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.Bet)
	if err != nil {
		err = msgp.WrapError(err, "Bet")
		return
	}
	// write "Players"
	err = en.Append(0xa7, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Players)))
	if err != nil {
		err = msgp.WrapError(err, "Players")
		return
	}
	for za0001 := range z.Players {
		err = en.WriteInt32(z.Players[za0001])
		if err != nil {
			err = msgp.WrapError(err, "Players", za0001)
			return
		}
	}
	// write "Winners"
	err = en.Append(0xa7, 0x57, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Winners)))
	if err != nil {
		err = msgp.WrapError(err, "Winners")
		return
	}
	for za0002 := range z.Winners {
		err = en.WriteInt32(z.Winners[za0002])
		if err != nil {
			err = msgp.WrapError(err, "Winners", za0002)
			return
		}
	}
	// write "Coin"
	err = en.Append(0xa4, 0x43, 0x6f, 0x69, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.Coin)
	if err != nil {
		err = msgp.WrapError(err, "Coin")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *ActionAck) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 7
	// string "Type"
	o = append(o, 0x87, 0xa4, 0x54, 0x79, 0x70, 0x65)
	o = msgp.AppendInt32(o, int32(z.Type))
	// string "Poker"
	o = append(o, 0xa5, 0x50, 0x6f, 0x6b, 0x65, 0x72)
	o = msgp.AppendBytes(o, z.Poker)
	// string "Uid"
	o = append(o, 0xa3, 0x55, 0x69, 0x64)
	o = msgp.AppendInt32(o, z.Uid)
	// string "Bet"
	o = append(o, 0xa3, 0x42, 0x65, 0x74)
	o = msgp.AppendInt32(o, z.Bet)
	// string "Players"
	o = append(o, 0xa7, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Players)))
	for za0001 := range z.Players {
		o = msgp.AppendInt32(o, z.Players[za0001])
	}
	// string "Winners"
	o = append(o, 0xa7, 0x57, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Winners)))
	for za0002 := range z.Winners {
		o = msgp.AppendInt32(o, z.Winners[za0002])
	}
	// string "Coin"
	o = append(o, 0xa4, 0x43, 0x6f, 0x69, 0x6e)
	o = msgp.AppendInt64(o, z.Coin)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *ActionAck) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Type":
			{
				var zb0002 int32
				zb0002, bts, err = msgp.ReadInt32Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Type")
					return
				}
				z.Type = ActionType(zb0002)
			}
		case "Poker":
			z.Poker, bts, err = msgp.ReadBytesBytes(bts, z.Poker)
			if err != nil {
				err = msgp.WrapError(err, "Poker")
				return
			}
		case "Uid":
			z.Uid, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Uid")
				return
			}
		case "Bet":
			z.Bet, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Bet")
				return
			}
		case "Players":
			var zb0003 uint32
			zb0003, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Players")
				return
			}
			if cap(z.Players) >= int(zb0003) {
				z.Players = (z.Players)[:zb0003]
			} else {
				z.Players = make([]int32, zb0003)
			}
			for za0001 := range z.Players {
				z.Players[za0001], bts, err = msgp.ReadInt32Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Players", za0001)
					return
				}
			}
		case "Winners":
			var zb0004 uint32
			zb0004, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Winners")
				return
			}
			if cap(z.Winners) >= int(zb0004) {
				z.Winners = (z.Winners)[:zb0004]
			} else {
				z.Winners = make([]int32, zb0004)
			}
			for za0002 := range z.Winners {
				z.Winners[za0002], bts, err = msgp.ReadInt32Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Winners", za0002)
					return
				}
			}
		case "Coin":
			z.Coin, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Coin")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *ActionAck) Msgsize() (s int) {
	s = 1 + 5 + msgp.Int32Size + 6 + msgp.BytesPrefixSize + len(z.Poker) + 4 + msgp.Int32Size + 4 + msgp.Int32Size + 8 + msgp.ArrayHeaderSize + (len(z.Players) * (msgp.Int32Size)) + 8 + msgp.ArrayHeaderSize + (len(z.Winners) * (msgp.Int32Size)) + 5 + msgp.Int64Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *ActionReq) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Type":
			{
				var zb0002 int32
				zb0002, err = dc.ReadInt32()
				if err != nil {
					err = msgp.WrapError(err, "Type")
					return
				}
				z.Type = ActionType(zb0002)
			}
		case "Bet":
			z.Bet, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "Bet")
				return
			}
		case "Opponent":
			z.Opponent, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "Opponent")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z ActionReq) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "Type"
	err = en.Append(0x83, 0xa4, 0x54, 0x79, 0x70, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt32(int32(z.Type))
	if err != nil {
		err = msgp.WrapError(err, "Type")
		return
	}
	// write "Bet"
	err = en.Append(0xa3, 0x42, 0x65, 0x74)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.Bet)
	if err != nil {
		err = msgp.WrapError(err, "Bet")
		return
	}
	// write "Opponent"
	err = en.Append(0xa8, 0x4f, 0x70, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.Opponent)
	if err != nil {
		err = msgp.WrapError(err, "Opponent")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z ActionReq) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "Type"
	o = append(o, 0x83, 0xa4, 0x54, 0x79, 0x70, 0x65)
	o = msgp.AppendInt32(o, int32(z.Type))
	// string "Bet"
	o = append(o, 0xa3, 0x42, 0x65, 0x74)
	o = msgp.AppendInt32(o, z.Bet)
	// string "Opponent"
	o = append(o, 0xa8, 0x4f, 0x70, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74)
	o = msgp.AppendInt32(o, z.Opponent)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *ActionReq) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Type":
			{
				var zb0002 int32
				zb0002, bts, err = msgp.ReadInt32Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Type")
					return
				}
				z.Type = ActionType(zb0002)
			}
		case "Bet":
			z.Bet, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Bet")
				return
			}
		case "Opponent":
			z.Opponent, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Opponent")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z ActionReq) Msgsize() (s int) {
	s = 1 + 5 + msgp.Int32Size + 4 + msgp.Int32Size + 9 + msgp.Int32Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *ActionType) DecodeMsg(dc *msgp.Reader) (err error) {
	{
		var zb0001 int32
		zb0001, err = dc.ReadInt32()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = ActionType(zb0001)
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z ActionType) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteInt32(int32(z))
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z ActionType) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendInt32(o, int32(z))
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *ActionType) UnmarshalMsg(bts []byte) (o []byte, err error) {
	{
		var zb0001 int32
		zb0001, bts, err = msgp.ReadInt32Bytes(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = ActionType(zb0001)
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z ActionType) Msgsize() (s int) {
	s = msgp.Int32Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *Code) DecodeMsg(dc *msgp.Reader) (err error) {
	{
		var zb0001 int32
		zb0001, err = dc.ReadInt32()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = Code(zb0001)
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z Code) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteInt32(int32(z))
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z Code) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendInt32(o, int32(z))
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Code) UnmarshalMsg(bts []byte) (o []byte, err error) {
	{
		var zb0001 int32
		zb0001, bts, err = msgp.ReadInt32Bytes(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = Code(zb0001)
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z Code) Msgsize() (s int) {
	s = msgp.Int32Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *GameInitAck) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Table":
			z.Table, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "Table")
				return
			}
		case "Id":
			z.Id, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "Id")
				return
			}
		case "Pool":
			z.Pool, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "Pool")
				return
			}
		case "State":
			z.State, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "State")
				return
			}
		case "Ring":
			z.Ring, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "Ring")
				return
			}
		case "Players":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Players")
				return
			}
			if cap(z.Players) >= int(zb0002) {
				z.Players = (z.Players)[:zb0002]
			} else {
				z.Players = make([]*Player, zb0002)
			}
			for za0001 := range z.Players {
				if dc.IsNil() {
					err = dc.ReadNil()
					if err != nil {
						err = msgp.WrapError(err, "Players", za0001)
						return
					}
					z.Players[za0001] = nil
				} else {
					if z.Players[za0001] == nil {
						z.Players[za0001] = new(Player)
					}
					err = z.Players[za0001].DecodeMsg(dc)
					if err != nil {
						err = msgp.WrapError(err, "Players", za0001)
						return
					}
				}
			}
		case "Poker":
			z.Poker, err = dc.ReadBytes(z.Poker)
			if err != nil {
				err = msgp.WrapError(err, "Poker")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *GameInitAck) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 7
	// write "Table"
	err = en.Append(0x87, 0xa5, 0x54, 0x61, 0x62, 0x6c, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.Table)
	if err != nil {
		err = msgp.WrapError(err, "Table")
		return
	}
	// write "Id"
	err = en.Append(0xa2, 0x49, 0x64)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.Id)
	if err != nil {
		err = msgp.WrapError(err, "Id")
		return
	}
	// write "Pool"
	err = en.Append(0xa4, 0x50, 0x6f, 0x6f, 0x6c)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.Pool)
	if err != nil {
		err = msgp.WrapError(err, "Pool")
		return
	}
	// write "State"
	err = en.Append(0xa5, 0x53, 0x74, 0x61, 0x74, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.State)
	if err != nil {
		err = msgp.WrapError(err, "State")
		return
	}
	// write "Ring"
	err = en.Append(0xa4, 0x52, 0x69, 0x6e, 0x67)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.Ring)
	if err != nil {
		err = msgp.WrapError(err, "Ring")
		return
	}
	// write "Players"
	err = en.Append(0xa7, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Players)))
	if err != nil {
		err = msgp.WrapError(err, "Players")
		return
	}
	for za0001 := range z.Players {
		if z.Players[za0001] == nil {
			err = en.WriteNil()
			if err != nil {
				return
			}
		} else {
			err = z.Players[za0001].EncodeMsg(en)
			if err != nil {
				err = msgp.WrapError(err, "Players", za0001)
				return
			}
		}
	}
	// write "Poker"
	err = en.Append(0xa5, 0x50, 0x6f, 0x6b, 0x65, 0x72)
	if err != nil {
		return
	}
	err = en.WriteBytes(z.Poker)
	if err != nil {
		err = msgp.WrapError(err, "Poker")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *GameInitAck) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 7
	// string "Table"
	o = append(o, 0x87, 0xa5, 0x54, 0x61, 0x62, 0x6c, 0x65)
	o = msgp.AppendInt32(o, z.Table)
	// string "Id"
	o = append(o, 0xa2, 0x49, 0x64)
	o = msgp.AppendInt32(o, z.Id)
	// string "Pool"
	o = append(o, 0xa4, 0x50, 0x6f, 0x6f, 0x6c)
	o = msgp.AppendInt64(o, z.Pool)
	// string "State"
	o = append(o, 0xa5, 0x53, 0x74, 0x61, 0x74, 0x65)
	o = msgp.AppendInt32(o, z.State)
	// string "Ring"
	o = append(o, 0xa4, 0x52, 0x69, 0x6e, 0x67)
	o = msgp.AppendInt32(o, z.Ring)
	// string "Players"
	o = append(o, 0xa7, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Players)))
	for za0001 := range z.Players {
		if z.Players[za0001] == nil {
			o = msgp.AppendNil(o)
		} else {
			o, err = z.Players[za0001].MarshalMsg(o)
			if err != nil {
				err = msgp.WrapError(err, "Players", za0001)
				return
			}
		}
	}
	// string "Poker"
	o = append(o, 0xa5, 0x50, 0x6f, 0x6b, 0x65, 0x72)
	o = msgp.AppendBytes(o, z.Poker)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *GameInitAck) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Table":
			z.Table, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Table")
				return
			}
		case "Id":
			z.Id, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Id")
				return
			}
		case "Pool":
			z.Pool, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Pool")
				return
			}
		case "State":
			z.State, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "State")
				return
			}
		case "Ring":
			z.Ring, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Ring")
				return
			}
		case "Players":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Players")
				return
			}
			if cap(z.Players) >= int(zb0002) {
				z.Players = (z.Players)[:zb0002]
			} else {
				z.Players = make([]*Player, zb0002)
			}
			for za0001 := range z.Players {
				if msgp.IsNil(bts) {
					bts, err = msgp.ReadNilBytes(bts)
					if err != nil {
						return
					}
					z.Players[za0001] = nil
				} else {
					if z.Players[za0001] == nil {
						z.Players[za0001] = new(Player)
					}
					bts, err = z.Players[za0001].UnmarshalMsg(bts)
					if err != nil {
						err = msgp.WrapError(err, "Players", za0001)
						return
					}
				}
			}
		case "Poker":
			z.Poker, bts, err = msgp.ReadBytesBytes(bts, z.Poker)
			if err != nil {
				err = msgp.WrapError(err, "Poker")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *GameInitAck) Msgsize() (s int) {
	s = 1 + 6 + msgp.Int32Size + 3 + msgp.Int32Size + 5 + msgp.Int64Size + 6 + msgp.Int32Size + 5 + msgp.Int32Size + 8 + msgp.ArrayHeaderSize
	for za0001 := range z.Players {
		if z.Players[za0001] == nil {
			s += msgp.NilSize
		} else {
			s += z.Players[za0001].Msgsize()
		}
	}
	s += 6 + msgp.BytesPrefixSize + len(z.Poker)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *GameResultAck) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Id":
			z.Id, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "Id")
				return
			}
		case "Winner":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Winner")
				return
			}
			if cap(z.Winner) >= int(zb0002) {
				z.Winner = (z.Winner)[:zb0002]
			} else {
				z.Winner = make([]int32, zb0002)
			}
			for za0001 := range z.Winner {
				z.Winner[za0001], err = dc.ReadInt32()
				if err != nil {
					err = msgp.WrapError(err, "Winner", za0001)
					return
				}
			}
		case "Prize":
			var zb0003 uint32
			zb0003, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Prize")
				return
			}
			if cap(z.Prize) >= int(zb0003) {
				z.Prize = (z.Prize)[:zb0003]
			} else {
				z.Prize = make([]int64, zb0003)
			}
			for za0002 := range z.Prize {
				z.Prize[za0002], err = dc.ReadInt64()
				if err != nil {
					err = msgp.WrapError(err, "Prize", za0002)
					return
				}
			}
		case "Coin":
			z.Coin, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "Coin")
				return
			}
		case "Poker":
			z.Poker, err = dc.ReadBytes(z.Poker)
			if err != nil {
				err = msgp.WrapError(err, "Poker")
				return
			}
		case "Lucky":
			z.Lucky, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "Lucky")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *GameResultAck) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 6
	// write "Id"
	err = en.Append(0x86, 0xa2, 0x49, 0x64)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.Id)
	if err != nil {
		err = msgp.WrapError(err, "Id")
		return
	}
	// write "Winner"
	err = en.Append(0xa6, 0x57, 0x69, 0x6e, 0x6e, 0x65, 0x72)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Winner)))
	if err != nil {
		err = msgp.WrapError(err, "Winner")
		return
	}
	for za0001 := range z.Winner {
		err = en.WriteInt32(z.Winner[za0001])
		if err != nil {
			err = msgp.WrapError(err, "Winner", za0001)
			return
		}
	}
	// write "Prize"
	err = en.Append(0xa5, 0x50, 0x72, 0x69, 0x7a, 0x65)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Prize)))
	if err != nil {
		err = msgp.WrapError(err, "Prize")
		return
	}
	for za0002 := range z.Prize {
		err = en.WriteInt64(z.Prize[za0002])
		if err != nil {
			err = msgp.WrapError(err, "Prize", za0002)
			return
		}
	}
	// write "Coin"
	err = en.Append(0xa4, 0x43, 0x6f, 0x69, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.Coin)
	if err != nil {
		err = msgp.WrapError(err, "Coin")
		return
	}
	// write "Poker"
	err = en.Append(0xa5, 0x50, 0x6f, 0x6b, 0x65, 0x72)
	if err != nil {
		return
	}
	err = en.WriteBytes(z.Poker)
	if err != nil {
		err = msgp.WrapError(err, "Poker")
		return
	}
	// write "Lucky"
	err = en.Append(0xa5, 0x4c, 0x75, 0x63, 0x6b, 0x79)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.Lucky)
	if err != nil {
		err = msgp.WrapError(err, "Lucky")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *GameResultAck) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 6
	// string "Id"
	o = append(o, 0x86, 0xa2, 0x49, 0x64)
	o = msgp.AppendInt32(o, z.Id)
	// string "Winner"
	o = append(o, 0xa6, 0x57, 0x69, 0x6e, 0x6e, 0x65, 0x72)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Winner)))
	for za0001 := range z.Winner {
		o = msgp.AppendInt32(o, z.Winner[za0001])
	}
	// string "Prize"
	o = append(o, 0xa5, 0x50, 0x72, 0x69, 0x7a, 0x65)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Prize)))
	for za0002 := range z.Prize {
		o = msgp.AppendInt64(o, z.Prize[za0002])
	}
	// string "Coin"
	o = append(o, 0xa4, 0x43, 0x6f, 0x69, 0x6e)
	o = msgp.AppendInt64(o, z.Coin)
	// string "Poker"
	o = append(o, 0xa5, 0x50, 0x6f, 0x6b, 0x65, 0x72)
	o = msgp.AppendBytes(o, z.Poker)
	// string "Lucky"
	o = append(o, 0xa5, 0x4c, 0x75, 0x63, 0x6b, 0x79)
	o = msgp.AppendInt64(o, z.Lucky)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *GameResultAck) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Id":
			z.Id, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Id")
				return
			}
		case "Winner":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Winner")
				return
			}
			if cap(z.Winner) >= int(zb0002) {
				z.Winner = (z.Winner)[:zb0002]
			} else {
				z.Winner = make([]int32, zb0002)
			}
			for za0001 := range z.Winner {
				z.Winner[za0001], bts, err = msgp.ReadInt32Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Winner", za0001)
					return
				}
			}
		case "Prize":
			var zb0003 uint32
			zb0003, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Prize")
				return
			}
			if cap(z.Prize) >= int(zb0003) {
				z.Prize = (z.Prize)[:zb0003]
			} else {
				z.Prize = make([]int64, zb0003)
			}
			for za0002 := range z.Prize {
				z.Prize[za0002], bts, err = msgp.ReadInt64Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Prize", za0002)
					return
				}
			}
		case "Coin":
			z.Coin, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Coin")
				return
			}
		case "Poker":
			z.Poker, bts, err = msgp.ReadBytesBytes(bts, z.Poker)
			if err != nil {
				err = msgp.WrapError(err, "Poker")
				return
			}
		case "Lucky":
			z.Lucky, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Lucky")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *GameResultAck) Msgsize() (s int) {
	s = 1 + 3 + msgp.Int32Size + 7 + msgp.ArrayHeaderSize + (len(z.Winner) * (msgp.Int32Size)) + 6 + msgp.ArrayHeaderSize + (len(z.Prize) * (msgp.Int64Size)) + 5 + msgp.Int64Size + 6 + msgp.BytesPrefixSize + len(z.Poker) + 6 + msgp.Int64Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *GameStartAck) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Id":
			z.Id, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "Id")
				return
			}
		case "Pool":
			z.Pool, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "Pool")
				return
			}
		case "Players":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Players")
				return
			}
			if cap(z.Players) >= int(zb0002) {
				z.Players = (z.Players)[:zb0002]
			} else {
				z.Players = make([]*Player, zb0002)
			}
			for za0001 := range z.Players {
				if dc.IsNil() {
					err = dc.ReadNil()
					if err != nil {
						err = msgp.WrapError(err, "Players", za0001)
						return
					}
					z.Players[za0001] = nil
				} else {
					if z.Players[za0001] == nil {
						z.Players[za0001] = new(Player)
					}
					err = z.Players[za0001].DecodeMsg(dc)
					if err != nil {
						err = msgp.WrapError(err, "Players", za0001)
						return
					}
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *GameStartAck) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "Id"
	err = en.Append(0x83, 0xa2, 0x49, 0x64)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.Id)
	if err != nil {
		err = msgp.WrapError(err, "Id")
		return
	}
	// write "Pool"
	err = en.Append(0xa4, 0x50, 0x6f, 0x6f, 0x6c)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.Pool)
	if err != nil {
		err = msgp.WrapError(err, "Pool")
		return
	}
	// write "Players"
	err = en.Append(0xa7, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Players)))
	if err != nil {
		err = msgp.WrapError(err, "Players")
		return
	}
	for za0001 := range z.Players {
		if z.Players[za0001] == nil {
			err = en.WriteNil()
			if err != nil {
				return
			}
		} else {
			err = z.Players[za0001].EncodeMsg(en)
			if err != nil {
				err = msgp.WrapError(err, "Players", za0001)
				return
			}
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *GameStartAck) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "Id"
	o = append(o, 0x83, 0xa2, 0x49, 0x64)
	o = msgp.AppendInt32(o, z.Id)
	// string "Pool"
	o = append(o, 0xa4, 0x50, 0x6f, 0x6f, 0x6c)
	o = msgp.AppendInt64(o, z.Pool)
	// string "Players"
	o = append(o, 0xa7, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Players)))
	for za0001 := range z.Players {
		if z.Players[za0001] == nil {
			o = msgp.AppendNil(o)
		} else {
			o, err = z.Players[za0001].MarshalMsg(o)
			if err != nil {
				err = msgp.WrapError(err, "Players", za0001)
				return
			}
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *GameStartAck) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Id":
			z.Id, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Id")
				return
			}
		case "Pool":
			z.Pool, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Pool")
				return
			}
		case "Players":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Players")
				return
			}
			if cap(z.Players) >= int(zb0002) {
				z.Players = (z.Players)[:zb0002]
			} else {
				z.Players = make([]*Player, zb0002)
			}
			for za0001 := range z.Players {
				if msgp.IsNil(bts) {
					bts, err = msgp.ReadNilBytes(bts)
					if err != nil {
						return
					}
					z.Players[za0001] = nil
				} else {
					if z.Players[za0001] == nil {
						z.Players[za0001] = new(Player)
					}
					bts, err = z.Players[za0001].UnmarshalMsg(bts)
					if err != nil {
						err = msgp.WrapError(err, "Players", za0001)
						return
					}
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *GameStartAck) Msgsize() (s int) {
	s = 1 + 3 + msgp.Int32Size + 5 + msgp.Int64Size + 8 + msgp.ArrayHeaderSize
	for za0001 := range z.Players {
		if z.Players[za0001] == nil {
			s += msgp.NilSize
		} else {
			s += z.Players[za0001].Msgsize()
		}
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *Player) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Id":
			z.Id, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "Id")
				return
			}
		case "Icon":
			z.Icon, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "Icon")
				return
			}
		case "Vip":
			z.Vip, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "Vip")
				return
			}
		case "Chair":
			z.Chair, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "Chair")
				return
			}
		case "Coin":
			z.Coin, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "Coin")
				return
			}
		case "Bet":
			z.Bet, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "Bet")
				return
			}
		case "Name":
			z.Name, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Name")
				return
			}
		case "State":
			{
				var zb0002 int32
				zb0002, err = dc.ReadInt32()
				if err != nil {
					err = msgp.WrapError(err, "State")
					return
				}
				z.State = Player_State(zb0002)
			}
		case "Look":
			z.Look, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "Look")
				return
			}
		case "Down":
			z.Down, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "Down")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Player) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 10
	// write "Id"
	err = en.Append(0x8a, 0xa2, 0x49, 0x64)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.Id)
	if err != nil {
		err = msgp.WrapError(err, "Id")
		return
	}
	// write "Icon"
	err = en.Append(0xa4, 0x49, 0x63, 0x6f, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.Icon)
	if err != nil {
		err = msgp.WrapError(err, "Icon")
		return
	}
	// write "Vip"
	err = en.Append(0xa3, 0x56, 0x69, 0x70)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.Vip)
	if err != nil {
		err = msgp.WrapError(err, "Vip")
		return
	}
	// write "Chair"
	err = en.Append(0xa5, 0x43, 0x68, 0x61, 0x69, 0x72)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.Chair)
	if err != nil {
		err = msgp.WrapError(err, "Chair")
		return
	}
	// write "Coin"
	err = en.Append(0xa4, 0x43, 0x6f, 0x69, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.Coin)
	if err != nil {
		err = msgp.WrapError(err, "Coin")
		return
	}
	// write "Bet"
	err = en.Append(0xa3, 0x42, 0x65, 0x74)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.Bet)
	if err != nil {
		err = msgp.WrapError(err, "Bet")
		return
	}
	// write "Name"
	err = en.Append(0xa4, 0x4e, 0x61, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Name)
	if err != nil {
		err = msgp.WrapError(err, "Name")
		return
	}
	// write "State"
	err = en.Append(0xa5, 0x53, 0x74, 0x61, 0x74, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt32(int32(z.State))
	if err != nil {
		err = msgp.WrapError(err, "State")
		return
	}
	// write "Look"
	err = en.Append(0xa4, 0x4c, 0x6f, 0x6f, 0x6b)
	if err != nil {
		return
	}
	err = en.WriteBool(z.Look)
	if err != nil {
		err = msgp.WrapError(err, "Look")
		return
	}
	// write "Down"
	err = en.Append(0xa4, 0x44, 0x6f, 0x77, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.Down)
	if err != nil {
		err = msgp.WrapError(err, "Down")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Player) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 10
	// string "Id"
	o = append(o, 0x8a, 0xa2, 0x49, 0x64)
	o = msgp.AppendInt32(o, z.Id)
	// string "Icon"
	o = append(o, 0xa4, 0x49, 0x63, 0x6f, 0x6e)
	o = msgp.AppendInt32(o, z.Icon)
	// string "Vip"
	o = append(o, 0xa3, 0x56, 0x69, 0x70)
	o = msgp.AppendInt32(o, z.Vip)
	// string "Chair"
	o = append(o, 0xa5, 0x43, 0x68, 0x61, 0x69, 0x72)
	o = msgp.AppendInt32(o, z.Chair)
	// string "Coin"
	o = append(o, 0xa4, 0x43, 0x6f, 0x69, 0x6e)
	o = msgp.AppendInt64(o, z.Coin)
	// string "Bet"
	o = append(o, 0xa3, 0x42, 0x65, 0x74)
	o = msgp.AppendInt64(o, z.Bet)
	// string "Name"
	o = append(o, 0xa4, 0x4e, 0x61, 0x6d, 0x65)
	o = msgp.AppendString(o, z.Name)
	// string "State"
	o = append(o, 0xa5, 0x53, 0x74, 0x61, 0x74, 0x65)
	o = msgp.AppendInt32(o, int32(z.State))
	// string "Look"
	o = append(o, 0xa4, 0x4c, 0x6f, 0x6f, 0x6b)
	o = msgp.AppendBool(o, z.Look)
	// string "Down"
	o = append(o, 0xa4, 0x44, 0x6f, 0x77, 0x6e)
	o = msgp.AppendInt32(o, z.Down)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Player) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Id":
			z.Id, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Id")
				return
			}
		case "Icon":
			z.Icon, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Icon")
				return
			}
		case "Vip":
			z.Vip, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Vip")
				return
			}
		case "Chair":
			z.Chair, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Chair")
				return
			}
		case "Coin":
			z.Coin, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Coin")
				return
			}
		case "Bet":
			z.Bet, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Bet")
				return
			}
		case "Name":
			z.Name, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Name")
				return
			}
		case "State":
			{
				var zb0002 int32
				zb0002, bts, err = msgp.ReadInt32Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "State")
					return
				}
				z.State = Player_State(zb0002)
			}
		case "Look":
			z.Look, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Look")
				return
			}
		case "Down":
			z.Down, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Down")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Player) Msgsize() (s int) {
	s = 1 + 3 + msgp.Int32Size + 5 + msgp.Int32Size + 4 + msgp.Int32Size + 6 + msgp.Int32Size + 5 + msgp.Int64Size + 4 + msgp.Int64Size + 5 + msgp.StringPrefixSize + len(z.Name) + 6 + msgp.Int32Size + 5 + msgp.BoolSize + 5 + msgp.Int32Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *Player_State) DecodeMsg(dc *msgp.Reader) (err error) {
	{
		var zb0001 int32
		zb0001, err = dc.ReadInt32()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = Player_State(zb0001)
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z Player_State) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteInt32(int32(z))
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z Player_State) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendInt32(o, int32(z))
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Player_State) UnmarshalMsg(bts []byte) (o []byte, err error) {
	{
		var zb0001 int32
		zb0001, bts, err = msgp.ReadInt32Bytes(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = Player_State(zb0001)
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z Player_State) Msgsize() (s int) {
	s = msgp.Int32Size
	return
}
